package com.botwithus.bot.scripts.slayerwithus.task;

import net.botwithus.rs3.game.Coordinate;

import java.util.List;

enum SlayerTaskLocationDefinition {
    MONKEYS_SHIPYARD(SlayerTask.MONKEYS, "shipyard", "Shipyard", 2909, 3023, 0, "Monkey"),
    MONKEYS_TAI_BWO_WANNAI_MINE(SlayerTask.MONKEYS, "tai_bwo_wannai_mine", "Tai Bwo Wannai mine", 2829, 3029, 0, "Monkey"),
    MONKEYS_JADE_VINE_MAZE(SlayerTask.MONKEYS, "jade_vine_maze", "Jade vine maze", 2895, 2994, 1, "Monkey"),
    MONKEYS_ARDOUGNE_ZOO(SlayerTask.MONKEYS, "ardougne_zoo", "Ardougne Zoo", 2600, 3275, 0, "Monkey"),
    MONKEYS_BRIMHAVEN(SlayerTask.MONKEYS, "brimhaven", "Brimhaven", 2732, 3176, 0, "Monkey"),
    MONKEYS_KARAMJA_VOLCANO(SlayerTask.MONKEYS, "karamja_volcano", "Karamja Volcano", 2820, 3193, 0, "Monkey"),
    MONKEYS_KHARAZI_JUNGLE(SlayerTask.MONKEYS, "kharazi_jungle", "Kharazi Jungle", 2880, 2934, 0, "Monkey"),
    MONKEYS_MUSA_POINT(SlayerTask.MONKEYS, "musa_point", "Musa Point", 2893, 3078, 0, "Monkey"),
    MONKEYS_TAI_BWO_WANNAI(SlayerTask.MONKEYS, "tai_bwo_wannai", "Tai Bwo Wannai", 2787, 3002, 0, "Monkey"),
    GOBLINS_LUMBRIDGE_CATACOMBS(SlayerTask.GOBLINS, "lumbridge_catacombs", "Lumbridge Catacombs", 4000, 5495, 0, "Skoblin"),
    GOBLINS_OBSERVATORY_DUNGEON(SlayerTask.GOBLINS, "observatory_dungeon", "Observatory Dungeon", 2305, 9385, 0, "Goblin"),
    GOBLINS_GOBLIN_CAVE(SlayerTask.GOBLINS, "goblin_cave", "Goblin Cave", 2564, 9836, 0, "Goblin"),
    GOBLINS_ARANDAR(SlayerTask.GOBLINS, "arandar", "Arandar", 2385, 3339, 0, "Goblin"),
    GOBLINS_CLOCK_TOWER_DUNGEON(SlayerTask.GOBLINS, "clock_tower_dungeon", "Clock Tower Dungeon", 2562, 9657, 0, "Goblin"),
    GOBLINS_FISHING_GUILD(SlayerTask.GOBLINS, "fishing_guild", "Fishing Guild", 2563, 3398, 0, "Goblin"),
    GOBLINS_MEIYERDITCH_TUNNELS(SlayerTask.GOBLINS, "meiyerditch_tunnels", "Meiyerditch tunnels", 3465, 9797, 0, "Goblin"),
    GOBLINS_PORT_SARIM(SlayerTask.GOBLINS, "port_sarim", "Port Sarim", 2995, 3209, 0, "Goblin"),
    GOBLINS_TREE_GNOME_VILLAGE_LOCATION(SlayerTask.GOBLINS, "tree_gnome_village_location", "Tree Gnome Village (location)", 2505, 3176, 0, "Goblin"),
    GOBLINS_UNDERGROUND_PASS_DUNGEON(SlayerTask.GOBLINS, "underground_pass_dungeon", "Underground Pass (dungeon)", 2377, 9657, 0, "Goblin"),
    GOBLINS_VARROCK(SlayerTask.GOBLINS, "varrock", "Varrock", 3118, 3432, 0, "Goblin"),
    GOBLINS_VARROCK_DIG_SITE(SlayerTask.GOBLINS, "varrock_dig_site", "Varrock Dig Site", 3312, 3370, 0, "Goblin"),
    RATS_WEST_ARDOUGNE(SlayerTask.RATS, "west_ardougne", "West Ardougne", 2461, 3293, 0, "Rat"),
    RATS_VARROCK_SEWERS(SlayerTask.RATS, "varrock_sewers", "Varrock Sewers", 3218, 9864, 0, "Rat"),
    RATS_UNDERGROUND_PASS_DUNGEON(SlayerTask.RATS, "underground_pass_dungeon", "Underground Pass (dungeon)", 2370, 9640, 0, "Rat"),
    RATS_ABANDONED_MINE(SlayerTask.RATS, "abandoned_mine", "Abandoned Mine", 2777, 4582, 0, "Rat"),
    RATS_ARDOUGNE_SEWERS_SOUTHERN_ARDOUGNE_SEWERS(SlayerTask.RATS, "ardougne_sewers_southern_ardougne_sewers", "Ardougne Sewers#Southern Ardougne Sewers", 2567, 9680, 0, "Rat"),
    RATS_BETTY(SlayerTask.RATS, "betty", "Betty", 3222, 4504, 0, "Rat"),
    RATS_BLACK_KNIGHTS_BASE(SlayerTask.RATS, "black_knights_base", "Black Knights' Base", 2930, 9701, 0, "Rat"),
    RATS_BLACK_KNIGHTS_CATACOMBS(SlayerTask.RATS, "black_knights_catacombs", "Black Knights' Catacombs", 1866, 4237, 0, "Rat"),
    RATS_BRIMHAVEN(SlayerTask.RATS, "brimhaven", "Brimhaven", 2807, 3167, 0, "Rat"),
    RATS_BURGH_DE_ROTT(SlayerTask.RATS, "burgh_de_rott", "Burgh de Rott", 3483, 3210, 0, "Rat"),
    RATS_CABIN_FEVER(SlayerTask.RATS, "cabin_fever", "Cabin Fever", 1814, 4826, 0, "Rat"),
    RATS_CLOCK_TOWER_DUNGEON(SlayerTask.RATS, "clock_tower_dungeon", "Clock Tower Dungeon", 2568, 9620, 0, "Rat"),
    RATS_CRANDOR_AND_KARAMJA_DUNGEON(SlayerTask.RATS, "crandor_and_karamja_dungeon", "Crandor and Karamja Dungeon", 300, 227, 0, "Rat"),
    RATS_DRAYNOR_MANOR(SlayerTask.RATS, "draynor_manor", "Draynor Manor", 3099, 3366, 0, "Rat"),
    RATS_DRAYNOR_SEWERS(SlayerTask.RATS, "draynor_sewers", "Draynor Sewers", 3083, 9673, 0, "Rat"),
    RATS_DRAYNOR_VILLAGE(SlayerTask.RATS, "draynor_village", "Draynor Village", 3100, 3273, 0, "Rat"),
    RATS_DWARVEN_MINES(SlayerTask.RATS, "dwarven_mines", "Dwarven mines", 3026, 9837, 0, "Rat"),
    RATS_EDGEVILLE(SlayerTask.RATS, "edgeville", "Edgeville", 3126, 3486, 0, "Rat"),
    RATS_EDGEVILLE_DUNGEON(SlayerTask.RATS, "edgeville_dungeon", "Edgeville Dungeon", 3112, 9884, 0, "Rat"),
    RATS_FALADOR_FARM(SlayerTask.RATS, "falador_farm", "Falador farm", 3019, 3289, 0, "Rat"),
    RATS_FISHING_GUILD(SlayerTask.RATS, "fishing_guild", "Fishing Guild", 2592, 3416, 0, "Rat"),
    RATS_GERTRUDE(SlayerTask.RATS, "gertrude", "Gertrude", 3151, 3414, 0, "Rat"),
    RATS_GNOME_MAZE(SlayerTask.RATS, "gnome_maze", "Gnome Maze", 2502, 3184, 0, "Rat"),
    RATS_GOBLIN_CAVE(SlayerTask.RATS, "goblin_cave", "Goblin Cave", 2573, 9805, 0, "Rat"),
    RATS_GRAND_TREE_MINE(SlayerTask.RATS, "grand_tree_mine", "Grand Tree mine", 2438, 9885, 0, "Rat"),
    RATS_GRAVEYARD_OF_SHADOWS(SlayerTask.RATS, "graveyard_of_shadows", "Graveyard of Shadows", 3251, 3677, 0, "Rat"),
    RATS_GU_TANOTH(SlayerTask.RATS, "gu_tanoth", "Gu'Tanoth", 2527, 2986, 0, "Rat"),
    RATS_HET_S_OASIS(SlayerTask.RATS, "het_s_oasis", "Het's Oasis", 3324, 3250, 0, "Rat"),
    RATS_LUMBRIDGE(SlayerTask.RATS, "lumbridge", "Lumbridge", 3205, 3203, 0, "Rat"),
    RATS_LUNAR_ISLE(SlayerTask.RATS, "lunar_isle", "Lunar Isle", 2117, 3887, 0, "Rat"),
    RATS_MCGRUBOR_S_WOOD(SlayerTask.RATS, "mcgrubor_s_wood", "McGrubor's Wood", 2610, 3479, 0, "Rat"),
    RATS_MEIYERDITCH_LABORATORIES(SlayerTask.RATS, "meiyerditch_laboratories", "Meiyerditch Laboratories", 3629, 9683, 0, "Rat"),
    RATS_MELZAR_S_MAZE(SlayerTask.RATS, "melzar_s_maze", "Melzar's Maze", 2923, 3251, 0, "Rat"),
    RATS_MOS_LE_HARMLESS(SlayerTask.RATS, "mos_le_harmless", "Mos Le'Harmless", 3682, 2948, 0, "Rat"),
    RATS_MYREQUE_HIDEOUT_THE_MEIYERDITCH_HIDEOUT(SlayerTask.RATS, "myreque_hideout_the_meiyerditch_hideout", "Myreque Hideout#The Meiyerditch Hideout", 3619, 9621, 0, "Rat"),
    RATS_MYREQUE_HIDEOUT_THE_MORT_MYRE_HIDEOUT(SlayerTask.RATS, "myreque_hideout_the_mort_myre_hideout", "Myreque Hideout#The Mort Myre Hideout", 3476, 9842, 0, "Rat"),
    RATS_NEW_VARROCK(SlayerTask.RATS, "new_varrock", "New Varrock", 3736, 9113, 0, "Rat"),
    RATS_OBSERVATORY_DUNGEON(SlayerTask.RATS, "observatory_dungeon", "Observatory Dungeon", 2339, 9356, 0, "Rat"),
    RATS_PIRATES_COVE(SlayerTask.RATS, "pirates_cove", "Pirates' Cove", 2223, 3793, 0, "Rat"),
    RATS_PORT_PHASMATYS(SlayerTask.RATS, "port_phasmatys", "Port Phasmatys", 3713, 3492, 0, "Rat"),
    RATS_PORT_SARIM(SlayerTask.RATS, "port_sarim", "Port Sarim", 3011, 3189, 0, "Rat"),
    RATS_RASHILIYIA_S_TOMB(SlayerTask.RATS, "rashiliyia_s_tomb", "Rashiliyia's Tomb", 2899, 9520, 0, "Rat"),
    RATS_RAT_CATCHERS_MANSION(SlayerTask.RATS, "rat_catchers_mansion", "Rat Catchers Mansion", 2857, 5091, 0, "Rat"),
    RATS_RIMMINGTON(SlayerTask.RATS, "rimmington", "Rimmington", 2955, 3193, 0, "Rat"),
    RATS_RUINS_EAST(SlayerTask.RATS, "ruins_east", "Ruins (east)", 3247, 3730, 0, "Rat"),
    RATS_RUINS_WEST(SlayerTask.RATS, "ruins_west", "Ruins (west)", 2996, 3700, 0, "Rat"),
    RATS_SHADOW_DUNGEON(SlayerTask.RATS, "shadow_dungeon", "Shadow Dungeon", 2693, 5111, 0, "Rat"),
    RATS_SINCLAIR_MANSION(SlayerTask.RATS, "sinclair_mansion", "Sinclair Mansion", 2720, 3583, 0, "Rat"),
    RATS_SKAVID_CAVES(SlayerTask.RATS, "skavid_caves", "Skavid caves", 2501, 9430, 0, "Rat"),
    RATS_SPIRIT_REALM(SlayerTask.RATS, "spirit_realm", "Spirit Realm", 2960, 4280, 0, "Rat"),
    RATS_STRONGHOLD_OF_SECURITY(SlayerTask.RATS, "stronghold_of_security", "Stronghold of Security", 3, 113, 0, "Rat"),
    RATS_WATERFALL_DUNGEON(SlayerTask.RATS, "waterfall_dungeon", "Waterfall Dungeon", 2542, 9897, 0, "Rat"),
    RATS_WILDERNESS_CRATER(SlayerTask.RATS, "wilderness_crater", "Wilderness Crater", 3156, 3634, 0, "Rat"),
    SPIDERS_LUMBRIDGE_CATACOMBS(SlayerTask.SPIDERS, "lumbridge_catacombs", "Lumbridge Catacombs", 3988, 5554, 0, "Corpse spider"),
    SPIDERS_UNDERGROUND_PASS(SlayerTask.SPIDERS, "underground_pass", "Underground Pass", 2395, 9683, 0, "Blessed spider"),
    SPIDERS_UNDERGROUND_PASS_DUNGEON(SlayerTask.SPIDERS, "underground_pass_dungeon", "Underground Pass (dungeon)", 2329, 9898, 0, "Spider"),
    SPIDERS_CHAOS_TUNNELS(SlayerTask.SPIDERS, "chaos_tunnels", "Chaos Tunnels", 3287, 5483, 0, "Crypt spider"),
    SPIDERS_AL_KHARID(SlayerTask.SPIDERS, "al_kharid", "Al Kharid", 3319, 3139, 0, "Spider"),
    SPIDERS_APE_ATOLL_DUNGEON(SlayerTask.SPIDERS, "ape_atoll_dungeon", "Ape Atoll Dungeon", 2694, 9104, 0, "Spider"),
    SPIDERS_BARROWS(SlayerTask.SPIDERS, "barrows", "Barrows", 3566, 9693, 0, "Crypt spider"),
    SPIDERS_DRAYNOR_MANOR_DUNGEON(SlayerTask.SPIDERS, "draynor_manor_dungeon", "Draynor Manor#Dungeon", 3110, 9745, 0, "Spider"),
    SPIDERS_GNOME_MAZE(SlayerTask.SPIDERS, "gnome_maze", "Gnome Maze", 2535, 3181, 0, "Spider"),
    SPIDERS_JUNGLE_DEMON(SlayerTask.SPIDERS, "jungle_demon", "Jungle demon", 2697, 9171, 0, "Spider"),
    SPIDERS_LUMBRIDGE(SlayerTask.SPIDERS, "lumbridge", "Lumbridge", 3182, 3188, 0, "Spider"),
    SPIDERS_LUMBRIDGE_CASTLE_CELLAR(SlayerTask.SPIDERS, "lumbridge_castle_cellar", "Lumbridge Castle#Cellar", 3209, 9618, 0, "Spider"),
    SPIDERS_MARIM(SlayerTask.SPIDERS, "marim", "Marim", 2734, 2792, 0, "Spider"),
    SPIDERS_OGRE_ENCLAVE(SlayerTask.SPIDERS, "ogre_enclave", "Ogre Enclave", 2565, 9443, 0, "Spider"),
    SPIDERS_RASHILIYIA_S_TOMB(SlayerTask.SPIDERS, "rashiliyia_s_tomb", "Rashiliyia's Tomb", 2920, 9486, 0, "Spider"),
    SPIDERS_RED_DRAGON_ISLE(SlayerTask.SPIDERS, "red_dragon_isle", "Red Dragon Isle", 3161, 3885, 0, "Spider"),
    SPIDERS_RUINS_WEST(SlayerTask.SPIDERS, "ruins_west", "Ruins (west)", 2982, 3683, 0, "Spider"),
    SPIDERS_STRONGHOLD_OF_SECURITY(SlayerTask.SPIDERS, "stronghold_of_security", "Stronghold of Security", 15, 42, 0, "Spider"),
    SPIDERS_TAVERLEY_DUNGEON(SlayerTask.SPIDERS, "taverley_dungeon", "Taverley Dungeon", 2891, 9834, 0, "Spider"),
    SPIDERS_TEMPLE_OF_MARIMBO_DUNGEON(SlayerTask.SPIDERS, "temple_of_marimbo_dungeon", "Temple of Marimbo Dungeon", 2761, 9189, 0, "Spider"),
    SPIDERS_TEMPLE_TREKKING(SlayerTask.SPIDERS, "temple_trekking", "Temple Trekking", 2037, 5041, 0, "Spider"),
    SPIDERS_THE_ARC(SlayerTask.SPIDERS, "the_arc", "The Arc", 1370, 7728, 0, "Spider"),
    SPIDERS_VARROCK_SEWER(SlayerTask.SPIDERS, "varrock_sewer", "Varrock Sewer", 3206, 9880, 0, "Spider"),
    SPIDERS_YANILLE(SlayerTask.SPIDERS, "yanille", "Yanille", 2671, 3107, 0, "Spider"),
    BIRDS_BURTHORPE(SlayerTask.BIRDS, "burthorpe", "Burthorpe", 2885, 3476, 0, "Chicken"),
    BIRDS_LUMBRIDGE(SlayerTask.BIRDS, "lumbridge", "Lumbridge", 3230, 3297, 0, "Chicken"),
    BIRDS_TREE_GNOME_STRONGHOLD(SlayerTask.BIRDS, "tree_gnome_stronghold", "Tree Gnome Stronghold", 2378, 3433, 0, "Terrorbird"),
    BIRDS_ARPOSANDRA(SlayerTask.BIRDS, "arposandra", "Arposandra", 3550, 4552, 0, "Terrorbird"),
    BIRDS_BARBARIAN_OUTPOST(SlayerTask.BIRDS, "barbarian_outpost", "Barbarian Outpost", 2553, 3562, 0, "Chicken"),
    BIRDS_CHAMPIONS_GUILD(SlayerTask.BIRDS, "champions_guild", "Champions' Guild", 3196, 3352, 0, "Chicken"),
    BIRDS_DEATH_PLATEAU(SlayerTask.BIRDS, "death_plateau", "Death Plateau", 2816, 3561, 0, "Chicken"),
    BIRDS_ENTRANA(SlayerTask.BIRDS, "entrana", "Entrana", 2846, 3374, 0, "Chicken"),
    BIRDS_ETCETERIA(SlayerTask.BIRDS, "etceteria", "Etceteria", 2601, 3874, 0, "Chicken"),
    BIRDS_FALADOR_FARM(SlayerTask.BIRDS, "falador_farm", "Falador farm", 3019, 3287, 0, "Chicken"),
    BIRDS_FRED_THE_FARMER(SlayerTask.BIRDS, "fred_the_farmer", "Fred the Farmer", 3204, 3286, 0, "Chicken"),
    BIRDS_GNOME_MAZE(SlayerTask.BIRDS, "gnome_maze", "Gnome Maze", 2498, 3141, 0, "Terrorbird"),
    BIRDS_HEMENSTER(SlayerTask.BIRDS, "hemenster", "Hemenster", 2650, 3441, 0, "Chicken"),
    BIRDS_MISCELLANIA(SlayerTask.BIRDS, "miscellania", "Miscellania", 2537, 3892, 0, "Chicken"),
    BIRDS_MISCELLANIA_CASTLE(SlayerTask.BIRDS, "miscellania_castle", "Miscellania Castle", 2512, 3862, 0, "Chicken"),
    BIRDS_RELLEKKA(SlayerTask.BIRDS, "rellekka", "Rellekka", 2679, 3663, 0, "Chicken"),
    BIRDS_RIVER_LUM(SlayerTask.BIRDS, "river_lum", "River Lum", 3225, 3300, 0, "Chicken"),
    BIRDS_SINCLAIR_MANSION(SlayerTask.BIRDS, "sinclair_mansion", "Sinclair Mansion", 2735, 3559, 0, "Chicken"),
    BIRDS_SUNKEN_TUTORIAL_ISLAND(SlayerTask.BIRDS, "sunken_tutorial_island", "Sunken Tutorial Island", 5250, 789, 0, "Chicken"),
    BIRDS_TAI_BWO_WANNAI(SlayerTask.BIRDS, "tai_bwo_wannai", "Tai Bwo Wannai", 2780, 3064, 0, "Chicken"),
    BIRDS_TAVERLEY(SlayerTask.BIRDS, "taverley", "Taverley", 2884, 3475, 0, "Chicken"),
    BIRDS_TUTORIAL_ISLAND(SlayerTask.BIRDS, "tutorial_island", "Tutorial Island", 3842, 4246, 0, "Chicken"),
    BIRDS_TYRAS_CAMP(SlayerTask.BIRDS, "tyras_camp", "Tyras Camp", 2184, 3152, 0, "Chicken"),
    BIRDS_WHITE_KNIGHTS_CASTLE(SlayerTask.BIRDS, "white_knights_castle", "White Knights' Castle", 2966, 3346, 0, "Chicken"),
    BIRDS_WITCHAVEN(SlayerTask.BIRDS, "witchaven", "Witchaven", 2691, 3273, 0, "Chicken"),
    BIRDS_ZANARIS(SlayerTask.BIRDS, "zanaris", "Zanaris", 2451, 4477, 0, "Chicken"),
    COWS_LUMBRIDGE(SlayerTask.COWS, "lumbridge", "Lumbridge", 3259, 3262, 0, "Cow"),
    COWS_BURTHROPE(SlayerTask.COWS, "burthrope", "Burthrope", 2885, 3487, 0, "Cow"),
    COWS_MILL_LANE(SlayerTask.COWS, "mill_lane", "Lumbridge Mill Lane", 3185, 3326, 0, "Cow"),
    COWS_ASTRAM_FARM(SlayerTask.COWS, "astram_farm", "Astram Farm", 2882, 3490, 0, "Cow"),
    COWS_CRAFTING_GUILD(SlayerTask.COWS, "crafting_guild", "Crafting Guild", 2917, 3289, 0, "Cow"),
    COWS_FALADOR_FARM(SlayerTask.COWS, "falador_farm", "Falador Farm", 3027, 3307, 0, "Cow"),
    COWS_MILL_LANE_MILL(SlayerTask.COWS, "mill_lane_mill", "Mill Lane Mill", 3154, 3325, 0, "Cow"),
    COWS_SINCLAIR_MANSION(SlayerTask.COWS, "sinclair_mansion", "Sinclair Mansion", 2733, 3561, 0, "Cow"),
    COWS_YANILLE(SlayerTask.COWS, "yanille", "Yanille", 2580, 3117, 0, "Cow"),
    COWS_ZANARIS(SlayerTask.COWS, "zanaris", "Zanaris", 2435, 4442, 0, "Cow"),
    SCORPIONS_WILDERNESS(SlayerTask.SCORPIONS, "wilderness", "Wilderness", 3225, 3943, 0, "Scorpion"),
    SCORPIONS_DWARVEN_MINES(SlayerTask.SCORPIONS, "dwarven_mines", "Dwarven mines", 3038, 9771, 0, "Scorpion"),
    SCORPIONS_AL_KHARID_MINE(SlayerTask.SCORPIONS, "al_kharid_mine", "Al Kharid mine", 3292, 3297, 0, "Scorpion"),
    SCORPIONS_ARDOUGNE_ZOO(SlayerTask.SCORPIONS, "ardougne_zoo", "Ardougne Zoo", 2602, 3267, 0, "Scorpion"),
    SCORPIONS_CAIRN_ISLE(SlayerTask.SCORPIONS, "cairn_isle", "Cairn Isle", 2765, 2978, 0, "Scorpion"),
    SCORPIONS_KARAMJA_VOLCANO(SlayerTask.SCORPIONS, "karamja_volcano", "Karamja Volcano", 2843, 3156, 0, "Scorpion"),
    SCORPIONS_STRONGHOLD_OF_SECURITY_PIT_OF_PESTILENCE_3RD_LEVEL(SlayerTask.SCORPIONS, "stronghold_of_security_pit_of_pestilence_3rd_level", "Stronghold of Security#Pit of Pestilence (3rd level)", 65, 58, 0, "Scorpion"),
    SCORPIONS_TEMPLE_OF_IKOV_DUNGEON(SlayerTask.SCORPIONS, "temple_of_ikov_dungeon", "Temple of Ikov (dungeon)", 2637, 9809, 0, "Scorpion"),
    SCORPIONS_VARROCK_SEWERS(SlayerTask.SCORPIONS, "varrock_sewers", "Varrock Sewers", 3251, 9908, 0, "Scorpion"),
    BATS_ABANDONED_MINE(SlayerTask.BATS, "abandoned_mine", "Abandoned Mine", 3409, 9637, 0, "Bat"),
    BATS_HAUNTED_WOODS(SlayerTask.BATS, "haunted_woods", "Haunted Woods", 3565, 3503, 0, "Bat"),
    BATS_PATERDOMUS(SlayerTask.BATS, "paterdomus", "Paterdomus", 3341, 3478, 0, "Bat"),
    BATS_SHADOW_DUNGEON(SlayerTask.BATS, "shadow_dungeon", "Shadow dungeon", 2693, 5102, 0, "Bat"),
    BATS_SLAYER_TOWER(SlayerTask.BATS, "slayer_tower", "Slayer tower", 3411, 3550, 0, "Bat"),
    WOLVES_KHARIDIAN_DESERT(SlayerTask.WOLVES, "kharidian_desert", "Kharidian Desert", 3150, 3044, 0, "Desert wolf"),
    WOLVES_WHITE_WOLF_MOUNTAIN(SlayerTask.WOLVES, "white_wolf_mountain", "White Wolf Mountain", 2861, 3455, 0, "Adolescent White wolf"),
    WOLVES_ICE_PATH(SlayerTask.WOLVES, "ice_path", "Ice Path", 2886, 3723, 0, "Ice wolf"),
    WOLVES_GOD_WARS_DUNGEON(SlayerTask.WOLVES, "god_wars_dungeon", "God Wars Dungeon", 2926, 3754, 0, "Ice wolf"),
    WOLVES_TROLLWEISS_MOUNTAIN(SlayerTask.WOLVES, "trollweiss_mountain", "Trollweiss Mountain", 2761, 3863, 0, "Ice wolf"),
    ZOMBIES_LUMBRIDGE_CATACOMBS(SlayerTask.ZOMBIES, "lumbridge_catacombs", "Lumbridge Catacombs", 3988, 5554, 0, "Corpse spider"),
    ZOMBIES_SLAYER_TOWER(SlayerTask.ZOMBIES, "slayer_tower", "Slayer Tower", 3401, 3563, 0, "Crawling hand"),
    ZOMBIES_FORT_FORINTHRY_NORTH(SlayerTask.ZOMBIES, "fort_forinthry_north", "North of Fort Forinthry", 3272, 3578, 0, "Fetid zombie"),
    ZOMBIES_BURTHORPE_SLAYER_CAVE(SlayerTask.ZOMBIES, "burthorpe_slayer_cave", "Burthorpe Slayer Cave", 223, 99, 0, "Crawling hand"),
    ZOMBIES_CRYPT_WILDERNESS(SlayerTask.ZOMBIES, "crypt_wilderness", "Crypt (Wilderness)", 3265, 3582, 0, "Fetid zombie"),
    SKELETONS_LUMBRIDGE_CATACOMBS(SlayerTask.SKELETONS, "lumbridge_catacombs", "Lumbridge Catacombs", 4000, 5495, 0, "Skoblin"),
    SKELETONS_EDGEVILLE_DUNGEON(SlayerTask.SKELETONS, "edgeville_dungeon", "Edgeville Dungeon", 3094, 9889, 0, "Skeleton"),
    SKELETONS_WILDERNESS(SlayerTask.SKELETONS, "wilderness", "Wilderness", 3072, 3531, 0, "Skeleton"),
    SKELETONS_TEMPLE_OF_IKOV_DUNGEON(SlayerTask.SKELETONS, "temple_of_ikov_dungeon", "Temple of Ikov (dungeon)", 2658, 9820, 0, "Skeleton"),
    SKELETONS_CRANDOR(SlayerTask.SKELETONS, "crandor", "Crandor", 2820, 3259, 0, "Skeleton"),
    SKELETONS_CRANDOR_AND_KARAMJA_DUNGEON(SlayerTask.SKELETONS, "crandor_and_karamja_dungeon", "Crandor and Karamja Dungeon", 288, 173, 0, "Skeleton"),
    SKELETONS_DRAYNOR_SEWERS(SlayerTask.SKELETONS, "draynor_sewers", "Draynor Sewers", 3101, 9671, 0, "Skeleton"),
    SKELETONS_GLARIAL_S_TOMB(SlayerTask.SKELETONS, "glarial_s_tomb", "Glarial's Tomb", 2529, 9841, 0, "Skeleton"),
    SKELETONS_OGRE_ENCLAVE(SlayerTask.SKELETONS, "ogre_enclave", "Ogre Enclave", 2576, 9436, 0, "Skeleton"),
    SKELETONS_SENNTISTEN_TEMPLE(SlayerTask.SKELETONS, "senntisten_temple", "Senntisten Temple", 3142, 5708, 0, "Skeleton"),
    SKELETONS_STRONGHOLD_OF_SECURITY_SEPULCHRE_OF_DEATH_4TH_LEVEL(SlayerTask.SKELETONS, "stronghold_of_security_sepulchre_of_death_4th_level", "Stronghold of Security#Sepulchre of Death (4th level)", 101, 3, 0, "Skeleton"),
    SKELETONS_TAVERLEY_DUNGEON(SlayerTask.SKELETONS, "taverley_dungeon", "Taverley Dungeon", 2882, 9826, 0, "Skeleton"),
    SKELETONS_UNDERGROUND_PASS_DUNGEON(SlayerTask.SKELETONS, "underground_pass_dungeon", "Underground Pass (dungeon)", 2371, 9611, 0, "Skeleton"),
    SKELETONS_VARROCK_SEWERS(SlayerTask.SKELETONS, "varrock_sewers", "Varrock Sewers", 3210, 9908, 0, "Skeleton"),
    SKELETONS_WATERFALL_DUNGEON(SlayerTask.SKELETONS, "waterfall_dungeon", "Waterfall Dungeon", 2586, 9884, 0, "Skeleton"),
    SKELETONS_WILDERNESS_LEVEL_9_SOUTH_WEST_MINE(SlayerTask.SKELETONS, "wilderness_level_9_south_west_mine", "Wilderness (level 9) south-west mine", 3008, 3595, 0, "Skeleton"),
    SKELETONS_WILDERNESS_AGILITY_COURSE_PIT(SlayerTask.SKELETONS, "wilderness_agility_course_pit", "Wilderness Agility Course Pit", 2994, 10346, 0, "Skeleton"),
    SKELETONS_WILDERNESS_CRATER(SlayerTask.SKELETONS, "wilderness_crater", "Wilderness Crater", 3092, 3717, 0, "Skeleton"),
    SKELETONS_YANILLE_AGILITY_DUNGEON(SlayerTask.SKELETONS, "yanille_agility_dungeon", "Yanille Agility dungeon", 66, 98, 0, "Skeleton"),
    GHOSTS_TAVERLEY_DUNGEON(SlayerTask.GHOSTS, "taverley_dungeon", "Taverley Dungeon", 2900, 9819, 0, "Ghost"),
    GHOSTS_BONEYARD(SlayerTask.GHOSTS, "boneyard", "Boneyard", 3272, 3664, 0, "Ghost"),
    GHOSTS_DEATH_RUNE_TEMPLE(SlayerTask.GHOSTS, "death_rune_temple", "Death Rune Temple", 2188, 4855, 0, "Ghost"),
    GHOSTS_DRAYNOR_MANOR(SlayerTask.GHOSTS, "draynor_manor", "Draynor Manor", 3094, 3356, 1, "Ghost"),
    GHOSTS_THE_FORGOTTEN_CEMETERY(SlayerTask.GHOSTS, "the_forgotten_cemetery", "The Forgotten Cemetery", 2962, 3755, 0, "Ghost"),
    GHOSTS_UZER(SlayerTask.GHOSTS, "uzer", "Uzer", 2714, 4892, 0, "Ghost"),
    GHOSTS_VARROCK_SEWERS(SlayerTask.GHOSTS, "varrock_sewers", "Varrock Sewers", 3241, 9913, 0, "Ghost"),
    GHOSTS_WEST_ARDOUGNE_GRAVEYARD(SlayerTask.GHOSTS, "west_ardougne_graveyard", "West Ardougne#Graveyard", 2501, 3289, 0, "Ghost"),
    BEARS_LEGENDS_GUILD_SOUTH_WEST_MINE(SlayerTask.BEARS, "legends_guild_south_west_mine", "Legends' Guild south-west mine", 2690, 3346, 0, "Grizzly bear"),
    BEARS_RELLEKKA(SlayerTask.BEARS, "rellekka", "Rellekka", 2689, 3612, 0, "Bear cub"),
    BEARS_ISAFDAR(SlayerTask.BEARS, "isafdar", "Isafdar", 2215, 3171, 0, "Grizzly bear"),
    BEARS_ARDOUGNE_ZOO(SlayerTask.BEARS, "ardougne_zoo", "Ardougne Zoo", 2632, 3280, 0, "Grizzly bear"),
    BEARS_RUINS_WEST(SlayerTask.BEARS, "ruins_west", "Ruins (west)", 2988, 3671, 0, "Grizzly bear"),
    BEARS_TREE_GNOME_VILLAGE_LOCATION(SlayerTask.BEARS, "tree_gnome_village_location", "Tree Gnome Village (location)", 2477, 3143, 0, "Grizzly bear"),
    BEARS_VARROCK(SlayerTask.BEARS, "varrock", "Varrock", 3230, 3500, 0, "Grizzly bear"),
    BEARS_WILDERNESS_CRATER(SlayerTask.BEARS, "wilderness_crater", "Wilderness Crater", 3100, 3594, 0, "Grizzly bear"),
    HILL_GIANTS_EDGEVILLE_DUNGEON(SlayerTask.HILL_GIANTS, "edgeville_dungeon", "Edgeville Dungeon", 3099, 9832, 0, "Hill Giant"),
    HILL_GIANTS_EDGEVILLE_DUNGEON_HILL_GIANT_RESOURCE_DUNGEON(SlayerTask.HILL_GIANTS, "edgeville_dungeon_hill_giant_resource_dungeon", "Edgeville Dungeon hill giant resource dungeon", 1108, 4580, 0, "Hill Giant"),
    HILL_GIANTS_OBSERVATORY(SlayerTask.HILL_GIANTS, "observatory", "Observatory", 2438, 3208, 0, "Hill Giant"),
    HILL_GIANTS_BONEYARD(SlayerTask.HILL_GIANTS, "boneyard", "Boneyard", 3300, 3649, 0, "Hill Giant"),
    HILL_GIANTS_TAVERLEY_DUNGEON(SlayerTask.HILL_GIANTS, "taverley_dungeon", "Taverley Dungeon", 2902, 9736, 0, "Hill Giant"),
    HILL_GIANTS_TREE_GNOME_STRONGHOLD(SlayerTask.HILL_GIANTS, "tree_gnome_stronghold", "Tree Gnome Stronghold", 2369, 3394, 0, "Hill Giant"),
    HILL_GIANTS_TREE_GNOME_VILLAGE_LOCATION(SlayerTask.HILL_GIANTS, "tree_gnome_village_location", "Tree Gnome Village (location)", 2507, 3149, 0, "Hill Giant"),
    ICE_GIANTS_CHAOS_TUNNELS(SlayerTask.ICE_GIANTS, "chaos_tunnels", "Chaos Tunnels", 3205, 5445, 0, "Ice giant"),
    ICE_GIANTS_WHITE_WOLF_MOUNTAIN(SlayerTask.ICE_GIANTS, "white_wolf_mountain", "White Wolf Mountain", 2805, 3514, 2, "Ice giant"),
    ICE_GIANTS_ASGARNIAN_ICE_DUNGEON(SlayerTask.ICE_GIANTS, "asgarnian_ice_dungeon", "Asgarnian Ice Dungeon", 3057, 9573, 0, "Ice giant"),
    ICE_GIANTS_ICE_QUEEN_S_LAIR(SlayerTask.ICE_GIANTS, "ice_queen_s_lair", "Ice Queen's Lair", 64, 71, 0, "Ice giant"),
    FIRE_GIANTS_CHAOS_TUNNELS(SlayerTask.FIRE_GIANTS, "chaos_tunnels", "Chaos Tunnels", 3220, 5496, 0, "Fire giant"),
    FIRE_GIANTS_BAXTORIAN_FALLS_RESOURCE_DUNGEON(SlayerTask.FIRE_GIANTS, "baxtorian_falls_resource_dungeon", "Baxtorian Falls resource dungeon", 1233, 4566, 0, "Fire giant"),
    FIRE_GIANTS_WATERFALL_DUNGEON(SlayerTask.FIRE_GIANTS, "waterfall_dungeon", "Waterfall Dungeon", 2562, 9886, 0, "Fire giant"),
    FIRE_GIANTS_BRIMHAVEN_DUNGEON(SlayerTask.FIRE_GIANTS, "brimhaven_dungeon", "Brimhaven Dungeon", 95, 72, 0, "Fire giant"),
    FIRE_GIANTS_SMOKE_DUNGEON(SlayerTask.FIRE_GIANTS, "smoke_dungeon", "Smoke Dungeon", 3244, 9356, 0, "Fire giant"),
    MOSS_GIANTS_CHAOS_TUNNELS(SlayerTask.MOSS_GIANTS, "chaos_tunnels", "Chaos Tunnels", 3200, 5495, 0, "Moss giant"),
    MOSS_GIANTS_PIRATES_COVE(SlayerTask.MOSS_GIANTS, "pirates_cove", "Pirates' Cove", 2195, 3808, 0, "Moss giant"),
    MOSS_GIANTS_VARROCK_SEWERS_RESOURCE_DUNGEON(SlayerTask.MOSS_GIANTS, "varrock_sewers_resource_dungeon", "Varrock Sewers resource dungeon", 1307, 4574, 0, "Moss giant"),
    MOSS_GIANTS_BRIMHAVEN_DUNGEON(SlayerTask.MOSS_GIANTS, "brimhaven_dungeon", "Brimhaven Dungeon", 76, 120, 0, "Moss giant"),
    MOSS_GIANTS_CRANDOR(SlayerTask.MOSS_GIANTS, "crandor", "Crandor", 2827, 3246, 0, "Moss giant"),
    MOSS_GIANTS_FISHING_GUILD(SlayerTask.MOSS_GIANTS, "fishing_guild", "Fishing Guild", 2549, 3408, 0, "Moss giant"),
    MOSS_GIANTS_MOSS_GIANT_ISLAND(SlayerTask.MOSS_GIANTS, "moss_giant_island", "Moss Giant Island", 2691, 3215, 0, "Moss giant"),
    MOSS_GIANTS_VARROCK_SEWERS(SlayerTask.MOSS_GIANTS, "varrock_sewers", "Varrock Sewers", 3157, 9905, 0, "Moss giant"),
    TROLLS_BURTHORPE_TROLL_CAVE(SlayerTask.TROLLS, "burthorpe_troll_cave", "Burthorpe Troll Cave", 2228, 4381, 0, "Troll shaman"),
    TROLLS_ICE_TROLL_CAVES(SlayerTask.TROLLS, "ice_troll_caves", "Ice Troll Caves", 2381, 10285, 0, "Ice troll female"),
    TROLLS_LUCIEN_S_CAMP(SlayerTask.TROLLS, "lucien_s_camp", "Lucien's camp", 2906, 3808, 0, "Undead troll"),
    TROLLS_CHAOS_TUNNELS(SlayerTask.TROLLS, "chaos_tunnels", "Chaos Tunnels", 3142, 5446, 0, "Ice troll female"),
    TROLLS_FREMENNIK_ISLES(SlayerTask.TROLLS, "fremennik_isles", "Fremennik Isles", 2336, 3834, 0, "Ice troll female"),
    TROLLS_JATIZSO_DUNGEON_MINE(SlayerTask.TROLLS, "jatizso_dungeon_mine", "Jatizso dungeon mine", 2401, 10217, 0, "Ice troll female"),
    ICE_WARRIORS_ASGARNIAN_ICE_DUNGEON(SlayerTask.ICE_WARRIORS, "asgarnian_ice_dungeon", "Asgarnian Ice Dungeon", 3044, 9581, 0, "Ice warrior"),
    ICE_WARRIORS_CHAOS_TUNNELS(SlayerTask.ICE_WARRIORS, "chaos_tunnels", "Chaos Tunnels", 3206, 5448, 0, "Ice warrior"),
    ICE_WARRIORS_WHITE_WOLF_MOUNTAIN(SlayerTask.ICE_WARRIORS, "white_wolf_mountain", "White Wolf Mountain", 2844, 3518, 1, "Ice warrior"),
    ICE_WARRIORS_ICE_QUEEN_S_LAIR(SlayerTask.ICE_WARRIORS, "ice_queen_s_lair", "Ice Queen's Lair", 6, 45, 0, "Ice warrior"),
    OGRES_GU_TANOTH(SlayerTask.OGRES, "gu_tanoth", "Gu'Tanoth", 2568, 2991, 0, "Ogre"),
    OGRES_YANILLE(SlayerTask.OGRES, "yanille", "Yanille", 2496, 3092, 0, "Ogre"),
    OGRES_COMBAT_TRAINING_CAMP(SlayerTask.OGRES, "combat_training_camp", "Combat Training Camp", 2523, 3373, 0, "Ogre"),
    OGRES_CHAOS_DRUID_TOWER(SlayerTask.OGRES, "chaos_druid_tower", "Chaos Druid Tower", 2581, 9738, 0, "Ogre"),
    OGRES_CLOCK_TOWER_DUNGEON(SlayerTask.OGRES, "clock_tower_dungeon", "Clock Tower Dungeon", 2585, 9608, 0, "Ogre"),
    OGRES_GNOME_MAZE(SlayerTask.OGRES, "gnome_maze", "Gnome Maze", 2554, 3192, 0, "Ogre"),
    OGRES_OGRE(SlayerTask.OGRES, "ogre", "Ogre", 1333, 5076, 2, "Ogre"),
    OGRES_UNDERGROUND_PASS_DUNGEON(SlayerTask.OGRES, "underground_pass_dungeon", "Underground Pass (dungeon)", 2387, 9685, 0, "Ogre"),
    OGRES_WITCHAVEN_DUNGEON(SlayerTask.OGRES, "witchaven_dungeon", "Witchaven Dungeon", 2719, 9668, 0, "Ogre"),
    HOBGOBLINS_HOBGOBLIN_PENINSULA(SlayerTask.HOBGOBLINS, "hobgoblin_peninsula", "Hobgoblin Peninsula", 2905, 3295, 0, "Hobgoblin"),
    HOBGOBLINS_OUTPOST(SlayerTask.HOBGOBLINS, "outpost", "Outpost", 2443, 3359, 0, "Hobgoblin"),
    HOBGOBLINS_ASGARNIA_ICE_DUNGEON(SlayerTask.HOBGOBLINS, "asgarnia_ice_dungeon", "Asgarnia Ice Dungeon", 3010, 9578, 0, "Hobgoblin"),
    HOBGOBLINS_CLOCK_TOWER_DUNGEON(SlayerTask.HOBGOBLINS, "clock_tower_dungeon", "Clock Tower Dungeon", 2566, 9632, 0, "Hobgoblin"),
    HOBGOBLINS_CRANDOR(SlayerTask.HOBGOBLINS, "crandor", "Crandor", 2818, 3291, 0, "Hobgoblin"),
    HOBGOBLINS_EDGEVILLE_DUNGEON(SlayerTask.HOBGOBLINS, "edgeville_dungeon", "Edgeville Dungeon", 3118, 9871, 0, "Hobgoblin"),
    HOBGOBLINS_GNOME_VILLAGE_DUNGEON(SlayerTask.HOBGOBLINS, "gnome_village_dungeon", "Gnome Village Dungeon", 2513, 9579, 0, "Hobgoblin"),
    HOBGOBLINS_MEIYERDITCH_LABORATORIES(SlayerTask.HOBGOBLINS, "meiyerditch_laboratories", "Meiyerditch Laboratories", 3469, 9796, 0, "Hobgoblin"),
    HOBGOBLINS_RELLEKKA(SlayerTask.HOBGOBLINS, "rellekka", "Rellekka", 2653, 3720, 0, "Hobgoblin"),
    HOBGOBLINS_TAI_BWO_WANNAI(SlayerTask.HOBGOBLINS, "tai_bwo_wannai", "Tai Bwo Wannai", 2787, 3013, 0, "Hobgoblin"),
    HOBGOBLINS_WATERBIRTH_ISLAND(SlayerTask.HOBGOBLINS, "waterbirth_island", "Waterbirth Island", 2503, 3730, 0, "Hobgoblin"),
    HOBGOBLINS_WITCHAVEN_DUNGEON(SlayerTask.HOBGOBLINS, "witchaven_dungeon", "Witchaven Dungeon", 2694, 9687, 0, "Hobgoblin"),
    DOGS_MCGRUBOR_S_WOOD(SlayerTask.DOGS, "mcgrubor_s_wood", "McGrubor's Wood", 2625, 3502, 0, "Guard dog"),
    DOGS_HANDELMORT_MANSION(SlayerTask.DOGS, "handelmort_mansion", "Handelmort Mansion", 2624, 3319, 0, "Guard dog"),
    DOGS_BRIMHAVEN(SlayerTask.DOGS, "brimhaven", "Brimhaven", 2784, 3191, 0, "Guard dog"),
    GHOULS_CANIFIS(SlayerTask.GHOULS, "canifis", "Canifis", 3483, 3533, 0, "Ghoul"),
    GHOULS_SLAYER_TOWER_MAUSOLEUM(SlayerTask.GHOULS, "slayer_tower_mausoleum", "Slayer Tower Mausoleum", 4431, 7898, 0, "Ravenous ghoul"),
    GREEN_DRAGONS_BONEYARD(SlayerTask.GREEN_DRAGONS, "boneyard", "Boneyard", 3331, 3672, 0, "Green dragon"),
    GREEN_DRAGONS_CHAOS_TUNNELS(SlayerTask.GREEN_DRAGONS, "chaos_tunnels", "Chaos Tunnels", 3303, 5452, 0, "Green dragon"),
    GREEN_DRAGONS_FORINTHRY_DUNGEON(SlayerTask.GREEN_DRAGONS, "forinthry_dungeon", "Forinthry Dungeon", 3105, 10063, 0, "Green dragon"),
    GREEN_DRAGONS_DARK_WARRIORS_FORTRESS(SlayerTask.GREEN_DRAGONS, "dark_warriors_fortress", "Dark Warriors' Fortress", 2973, 3620, 0, "Green dragon"),
    BLUE_DRAGONS_BLACK_KNIGHTS_FORTRESS(SlayerTask.BLUE_DRAGONS, "black_knights_fortress", "Black Knights' Fortress", 2967, 3535, 0, "Blue dragon"),
    BLUE_DRAGONS_TAVERLEY_BLUE_DRAGON_RESOURCE_DUNGEON(SlayerTask.BLUE_DRAGONS, "taverley_blue_dragon_resource_dungeon", "Taverley blue dragon resource dungeon", 967, 4498, 0, "Blue dragon"),
    BLUE_DRAGONS_OGRE_ENCLAVE(SlayerTask.BLUE_DRAGONS, "ogre_enclave", "Ogre Enclave", 2568, 9437, 0, "Blue dragon"),
    BLUE_DRAGONS_HEROES_GUILD_DUNGEON(SlayerTask.BLUE_DRAGONS, "heroes_guild_dungeon", "Heroes' Guild Dungeon", 220, 177, 0, "Blue dragon"),
    BLUE_DRAGONS_KURADAL_S_DUNGEON(SlayerTask.BLUE_DRAGONS, "kuradal_s_dungeon", "Kuradal's Dungeon", 67, 76, 0, "Blue dragon"),
    BLUE_DRAGONS_TAVERLEY_DUNGEON(SlayerTask.BLUE_DRAGONS, "taverley_dungeon", "Taverley Dungeon", 2897, 9797, 0, "Blue dragon"),
    RED_DRAGONS_RED_DRAGON_ISLE(SlayerTask.RED_DRAGONS, "red_dragon_isle", "Red Dragon Isle", 3190, 3834, 0, "Red dragon"),
    RED_DRAGONS_BRIMHAVEN_DUNGEON(SlayerTask.RED_DRAGONS, "brimhaven_dungeon", "Brimhaven Dungeon", 137, 98, 0, "Red dragon"),
    BLACK_DRAGONS_EVIL_CHICKEN_S_LAIR(SlayerTask.BLACK_DRAGONS, "evil_chicken_s_lair", "Evil Chicken's Lair", 1552, 4359, 0, "Black dragon"),
    BLACK_DRAGONS_LAVA_MAZE_DUNGEON(SlayerTask.BLACK_DRAGONS, "lava_maze_dungeon", "Lava Maze Dungeon", 3048, 10266, 0, "Black dragon"),
    BLACK_DRAGONS_TAVERLEY_DUNGEON(SlayerTask.BLACK_DRAGONS, "taverley_dungeon", "Taverley Dungeon", 2829, 9826, 0, "Black dragon"),
    LESSER_DEMONS_KARAMJA_VOLCANO_RESOURCE_DUNGEON(SlayerTask.LESSER_DEMONS, "karamja_volcano_resource_dungeon", "Karamja Volcano resource dungeon", 1164, 4569, 0, "Lesser demon"),
    LESSER_DEMONS_FORINTHRY_DUNGEON(SlayerTask.LESSER_DEMONS, "forinthry_dungeon", "Forinthry Dungeon", 3045, 10132, 0, "Lesser demon"),
    LESSER_DEMONS_TAVERLEY_DUNGEON(SlayerTask.LESSER_DEMONS, "taverley_dungeon", "Taverley Dungeon", 2926, 9802, 0, "Lesser demon"),
    LESSER_DEMONS_CRANDOR(SlayerTask.LESSER_DEMONS, "crandor", "Crandor", 2832, 3278, 0, "Lesser demon"),
    LESSER_DEMONS_CRANDOR_AND_KARAMJA_DUNGEON(SlayerTask.LESSER_DEMONS, "crandor_and_karamja_dungeon", "Crandor and Karamja Dungeon", 271, 154, 0, "Lesser demon"),
    LESSER_DEMONS_DEMONIC_RUINS(SlayerTask.LESSER_DEMONS, "demonic_ruins", "Demonic Ruins", 3324, 3856, 0, "Lesser demon"),
    LESSER_DEMONS_TEMPLE_OF_IKOV_DUNGEON(SlayerTask.LESSER_DEMONS, "temple_of_ikov_dungeon", "Temple of Ikov (dungeon)", 2630, 9867, 0, "Lesser demon"),
    LESSER_DEMONS_VIYELDI_CAVES(SlayerTask.LESSER_DEMONS, "viyeldi_caves", "Viyeldi caves", 2412, 4677, 0, "Lesser demon"),
    LESSER_DEMONS_WILDERNESS_CRATER(SlayerTask.LESSER_DEMONS, "wilderness_crater", "Wilderness Crater", 3096, 3691, 0, "Lesser demon"),
    GREATER_DEMONS_FORINTHRY_DUNGEON(SlayerTask.GREATER_DEMONS, "forinthry_dungeon", "Forinthry Dungeon", 3083, 10082, 0, "Greater demon"),
    GREATER_DEMONS_WILDERNESS_CRATER(SlayerTask.GREATER_DEMONS, "wilderness_crater", "Wilderness Crater", 3138, 3679, 0, "Greater demon"),
    GREATER_DEMONS_BRIMHAVEN_DUNGEON(SlayerTask.GREATER_DEMONS, "brimhaven_dungeon", "Brimhaven Dungeon", 2630, 9482, 0, "Greater demon"),
    GREATER_DEMONS_DEMONIC_RUINS(SlayerTask.GREATER_DEMONS, "demonic_ruins", "Demonic Ruins", 3286, 3875, 0, "Greater demon"),
    GREATER_DEMONS_ENTRANA_DUNGEON(SlayerTask.GREATER_DEMONS, "entrana_dungeon", "Entrana Dungeon", 2861, 9747, 0, "Greater demon"),
    GREATER_DEMONS_KURADAL_S_DUNGEON(SlayerTask.GREATER_DEMONS, "kuradal_s_dungeon", "Kuradal's Dungeon", 1603, 5256, 0, "Greater demon"),
    GREATER_DEMONS_OGRE_ENCLAVE(SlayerTask.GREATER_DEMONS, "ogre_enclave", "Ogre Enclave", 2586, 9458, 0, "Greater demon"),
    BLACK_DEMONS_TAVERLEY_DUNGEON(SlayerTask.BLACK_DEMONS, "taverley_dungeon", "Taverley Dungeon", 2854, 9776, 0, "Black demon"),
    BLACK_DEMONS_CHAOS_TUNNELS_RESOURCE_DUNGEON(SlayerTask.BLACK_DEMONS, "chaos_tunnels_resource_dungeon", "Chaos Tunnels resource dungeon", 1232, 4513, 0, "Black demon"),
    BLACK_DEMONS_DEMONIC_RUINS(SlayerTask.BLACK_DEMONS, "demonic_ruins", "Demonic Ruins", 3288, 3829, 0, "Black demon"),
    BLACK_DEMONS_BRIMHAVEN_DUNGEON(SlayerTask.BLACK_DEMONS, "brimhaven_dungeon", "Brimhaven Dungeon", 140, 81, 0, "Black demon"),
    BLACK_DEMONS_CHAOS_TUNNELS(SlayerTask.BLACK_DEMONS, "chaos_tunnels", "Chaos Tunnels", 3157, 5522, 0, "Black demon"),
    BLACK_DEMONS_EDGEVILLE_DUNGEON(SlayerTask.BLACK_DEMONS, "edgeville_dungeon", "Edgeville Dungeon", 3085, 9958, 0, "Black demon"),
    HELLHOUNDS_LAVA_MAZE(SlayerTask.HELLHOUNDS, "lava_maze", "Lava Maze", 3023, 3849, 0, "Hellhound"),
    HELLHOUNDS_DESERTED_KEEP(SlayerTask.HELLHOUNDS, "deserted_keep", "Deserted Keep", 3178, 3929, 0, "Hellhound"),
    HELLHOUNDS_TAVERLEY_DUNGEON(SlayerTask.HELLHOUNDS, "taverley_dungeon", "Taverley Dungeon", 2851, 9849, 0, "Hellhound"),
    HELLHOUNDS_FORINTHRY_DUNGEON(SlayerTask.HELLHOUNDS, "forinthry_dungeon", "Forinthry Dungeon", 3084, 10130, 0, "Hellhound"),
    HELLHOUNDS_KURADAL_S_DUNGEON(SlayerTask.HELLHOUNDS, "kuradal_s_dungeon", "Kuradal's Dungeon", 1637, 5254, 0, "Hellhound"),
    HELLHOUNDS_RUINS_EAST(SlayerTask.HELLHOUNDS, "ruins_east", "Ruins (east)", 3335, 3786, 0, "Hellhound"),
    HELLHOUNDS_TAVERLEY_HELLHOUND_RESOURCE_DUNGEON(SlayerTask.HELLHOUNDS, "taverley_hellhound_resource_dungeon", "Taverley hellhound resource dungeon", 1362, 4570, 0, "Hellhound"),
    HELLHOUNDS_WILDERNESS_CRATER(SlayerTask.HELLHOUNDS, "wilderness_crater", "Wilderness Crater", 3103, 3704, 0, "Hellhound"),
    HELLHOUNDS_WITCHAVEN_DUNGEON(SlayerTask.HELLHOUNDS, "witchaven_dungeon", "Witchaven Dungeon", 2734, 9688, 0, "Hellhound"),
    SHADOW_WARRIORS_LEGENDS_GUILD_DUNGEON(SlayerTask.SHADOW_WARRIORS, "legends_guild_dungeon", "Legends' Guild Dungeon", 2693, 9776, 0, "Shadow warrior"),
    WEREWOLVES_GOD_WARS_DUNGEON(SlayerTask.WEREWOLVES, "god_wars_dungeon", "God Wars Dungeon", 2835, 5286, 0, "Werewolf"),
    WEREWOLVES_FORINTHRY_DUNGEON(SlayerTask.WEREWOLVES, "forinthry_dungeon", "Forinthry Dungeon", 3095, 10168, 0, "Revenant werewolf"),
    VAMPYRES_BURGH_DE_ROTT_WOODS(SlayerTask.VAMPYRES, "burgh_de_rott_woods", "Burgh de Rott Woods", 3546, 3249, 0, "Vampyre Juvenile"),
    VAMPYRES_DARKMEYER(SlayerTask.VAMPYRES, "darkmeyer", "Darkmeyer", 3634, 3344, 0, "Vampyre Juvinate"),
    VAMPYRES_MEIYERDITCH(SlayerTask.VAMPYRES, "meiyerditch", "Meiyerditch", 3630, 3216, 0, "Vampyre Juvenile"),
    VAMPYRES_CASTLE_DRAKAN(SlayerTask.VAMPYRES, "castle_drakan", "Castle Drakan", 3527, 3351, 0, "Vampyre Juvenile"),
    DAGANNOTH_CHAOS_TUNNELS(SlayerTask.DAGANNOTH, "chaos_tunnels", "Chaos Tunnels", 3145, 5557, 0, "Dagannoth"),
    DAGANNOTH_WATERBIRTH_ISLAND_DUNGEON(SlayerTask.DAGANNOTH, "waterbirth_island_dungeon", "Waterbirth Island Dungeon", 11, 486, 0, "Dagannoth"),
    TUROTH_FREMENNIK_SLAYER_DUNGEON(SlayerTask.TUROTH, "fremennik_slayer_dungeon", "Fremennik Slayer Dungeon", 2719, 10011, 0, "Turoth"),
    TUROTH_CHAOS_TUNNELS(SlayerTask.TUROTH, "chaos_tunnels", "Chaos Tunnels", 3153, 5536, 0, "Turoth"),
    TUROTH_POLLNIVNEACH_SLAYER_DUNGEON(SlayerTask.TUROTH, "pollnivneach_slayer_dungeon", "Pollnivneach Slayer Dungeon", 106, 34, 0, "Turoth"),
    CAVE_CRAWLERS_FREMENNIK_SLAYER_DUNGEON(SlayerTask.CAVE_CRAWLERS, "fremennik_slayer_dungeon", "Fremennik Slayer Dungeon", 2781, 10000, 0, "Cave crawler"),
    CAVE_CRAWLERS_DORGESH_KAAN_SOUTH_DUNGEON(SlayerTask.CAVE_CRAWLERS, "dorgesh_kaan_south_dungeon", "Dorgesh-Kaan South Dungeon", 2708, 5214, 0, "Cave crawler"),
    CAVE_CRAWLERS_LUMBRIDGE_SWAMP_CAVES(SlayerTask.CAVE_CRAWLERS, "lumbridge_swamp_caves", "Lumbridge Swamp Caves", 3186, 9582, 0, "Cave crawler"),
    BANSHEES_SLAYER_TOWER(SlayerTask.BANSHEES, "slayer_tower", "Slayer Tower", 3434, 3566, 0, "Banshee"),
    CRAWLING_HANDS_SLAYER_TOWER(SlayerTask.CRAWLING_HANDS, "slayer_tower", "Slayer Tower", 3401, 3563, 0, "Crawling hand"),
    CRAWLING_HANDS_BURTHORPE_SLAYER_CAVE(SlayerTask.CRAWLING_HANDS, "burthorpe_slayer_cave", "Burthorpe Slayer Cave", 223, 99, 0, "Crawling hand"),
    INFERNAL_MAGES_CHAOS_TUNNELS(SlayerTask.INFERNAL_MAGES, "chaos_tunnels", "Chaos Tunnels", 3189, 5523, 0, "Infernal Mage"),
    INFERNAL_MAGES_SLAYER_TOWER(SlayerTask.INFERNAL_MAGES, "slayer_tower", "Slayer Tower", 3400, 3560, 1, "Infernal Mage"),
    ABERRANT_SPECTRES_SLAYER_TOWER(SlayerTask.ABERRANT_SPECTRES, "slayer_tower", "Slayer Tower", 3434, 3572, 1, "Aberrant spectre"),
    ABERRANT_SPECTRES_POLLNIVNEACH_SLAYER_DUNGEON(SlayerTask.ABERRANT_SPECTRES, "pollnivneach_slayer_dungeon", "Pollnivneach Slayer Dungeon", 111, 62, 0, "Aberrant spectre"),
    ABYSSAL_DEMONS_42_WILDERNESS(SlayerTask.ABYSSAL_DEMONS_42, "wilderness", "Wilderness", 3212, 3662, 0, "Abyssal demon"),
    ABYSSAL_DEMONS_42_MORYTANIA_SLAYER_TOWER_DUNGEON(SlayerTask.ABYSSAL_DEMONS_42, "morytania_slayer_tower_dungeon", "Morytania Slayer Tower dungeon", 1165, 4618, 0, "Abyssal demon"),
    ABYSSAL_DEMONS_42_SLAYER_TOWER(SlayerTask.ABYSSAL_DEMONS_42, "slayer_tower", "Slayer Tower", 3402, 3545, 2, "Abyssal demon"),
    ABYSSAL_DEMONS_42_ABYSSAL_AREA(SlayerTask.ABYSSAL_DEMONS_42, "abyssal_area", "Abyssal Area", 3016, 4891, 0, "Abyssal demon"),
    ABYSSAL_DEMONS_42_KURADAL_S_DUNGEON(SlayerTask.ABYSSAL_DEMONS_42, "kuradal_s_dungeon", "Kuradal's Dungeon", 94, 103, 0, "Abyssal demon"),
    BASILISKS_FREMENNIK_SLAYER_DUNGEON(SlayerTask.BASILISKS, "fremennik_slayer_dungeon", "Fremennik Slayer Dungeon", 2738, 10008, 0, "Basilisk"),
    BASILISKS_POLLNIVNEACH_SLAYER_DUNGEON(SlayerTask.BASILISKS, "pollnivneach_slayer_dungeon", "Pollnivneach Slayer Dungeon", 127, 5, 0, "Basilisk"),
    COCKATRICE_FREMENNIK_SLAYER_DUNGEON(SlayerTask.COCKATRICE, "fremennik_slayer_dungeon", "Fremennik Slayer Dungeon", 2785, 10035, 0, "Cockatrice"),
    KURASK_FREMENNIK_SLAYER_DUNGEON(SlayerTask.KURASK, "fremennik_slayer_dungeon", "Fremennik Slayer Dungeon", 2694, 9995, 0, "Kurask"),
    KURASK_POLLNIVNEACH_SLAYER_DUNGEON(SlayerTask.KURASK, "pollnivneach_slayer_dungeon", "Pollnivneach Slayer Dungeon", 98, 94, 0, "Kurask"),
    GARGOYLES_RUINS_EAST(SlayerTask.GARGOYLES, "ruins_east", "Ruins (east)", 3209, 3729, 0, "Gargoyle"),
    GARGOYLES_SLAYER_TOWER(SlayerTask.GARGOYLES, "slayer_tower", "Slayer Tower", 3435, 3549, 2, "Gargoyle"),
    GARGOYLES_CHAOS_TUNNELS(SlayerTask.GARGOYLES, "chaos_tunnels", "Chaos Tunnels", 3173, 5476, 0, "Gargoyle"),
    GARGOYLES_KURADAL_S_DUNGEON(SlayerTask.GARGOYLES, "kuradal_s_dungeon", "Kuradal's Dungeon", 71, 99, 0, "Gargoyle"),
    PYREFIENDS_SMOKE_DUNGEON(SlayerTask.PYREFIENDS, "smoke_dungeon", "Smoke Dungeon", 3248, 9374, 0, "Pyrefiend"),
    PYREFIENDS_FREMENNIK_SLAYER_DUNGEON(SlayerTask.PYREFIENDS, "fremennik_slayer_dungeon", "Fremennik Slayer Dungeon", 2757, 10008, 0, "Pyrefiend"),
    PYREFIENDS_SOUL_WARS(SlayerTask.PYREFIENDS, "soul_wars", "Soul Wars", 2161, 2929, 0, "Pyrefiend"),
    BLOODVELD_SLAYER_TOWER(SlayerTask.BLOODVELD, "slayer_tower", "Slayer Tower", 3400, 3547, 1, "Bloodveld"),
    BLOODVELD_MEIYERDITCH_TUNNELS_MEIYERDITCH_LABORATORY(SlayerTask.BLOODVELD, "meiyerditch_tunnels_meiyerditch_laboratory", "Meiyerditch tunnels#Meiyerditch laboratory", 3563, 9739, 0, "Bloodveld"),
    DUST_DEVILS_SMOKE_DUNGEON(SlayerTask.DUST_DEVILS, "smoke_dungeon", "Smoke Dungeon", 3213, 9361, 0, "Dust devil"),
    DUST_DEVILS_CHAOS_TUNNELS(SlayerTask.DUST_DEVILS, "chaos_tunnels", "Chaos Tunnels", 3166, 5513, 0, "Dust devil"),
    JELLIES_CHAOS_TUNNELS(SlayerTask.JELLIES, "chaos_tunnels", "Chaos Tunnels", 3267, 5447, 0, "Jelly"),
    JELLIES_SOUL_WARS(SlayerTask.JELLIES, "soul_wars", "Soul Wars", 2195, 2887, 0, "Jelly"),
    JELLIES_FREMENNIK_SLAYER_DUNGEON(SlayerTask.JELLIES, "fremennik_slayer_dungeon", "Fremennik Slayer Dungeon", 2699, 10029, 0, "Jelly"),
    JELLIES_JHALLAN_S_RESTING_PLACE(SlayerTask.JELLIES, "jhallan_s_resting_place", "Jhallan's resting place", 2833, 10342, 0, "Jelly"),
    ROCKSLUGS_FREMENNIK_SLAYER_DUNGEON(SlayerTask.ROCKSLUGS, "fremennik_slayer_dungeon", "Fremennik Slayer Dungeon", 2793, 10016, 0, "Rock slug"),
    ROCKSLUGS_LUMBRIDGE_SWAMP_CAVES(SlayerTask.ROCKSLUGS, "lumbridge_swamp_caves", "Lumbridge Swamp Caves", 3222, 9571, 0, "Rock slug"),
    ROCKSLUGS_DORGESH_KAAN_SOUTH_DUNGEON(SlayerTask.ROCKSLUGS, "dorgesh_kaan_south_dungeon", "Dorgesh-Kaan South Dungeon", 2727, 5223, 0, "Rock slug"),
    NECHRYAEL_SLAYER_TOWER(SlayerTask.NECHRYAEL, "slayer_tower", "Slayer Tower", 3402, 3567, 2, "Nechryael"),
    NECHRYAEL_HEART_OF_GIELINOR(SlayerTask.NECHRYAEL, "heart_of_gielinor", "Heart of Gielinor", 3122, 6910, 0, "Nechryael"),
    NECHRYAEL_CHAOS_TUNNELS(SlayerTask.NECHRYAEL, "chaos_tunnels", "Chaos Tunnels", 3165, 5557, 0, "Nechryael"),
    KALPHITE_KALPHITE_HIVE(SlayerTask.KALPHITE, "kalphite_hive", "Kalphite Hive", 3404, 9483, 0, "Kalphite Soldier"),
    EARTH_WARRIORS_EDGEVILLE_DUNGEON(SlayerTask.EARTH_WARRIORS, "edgeville_dungeon", "Edgeville Dungeon", 3118, 9974, 0, "Earth warrior"),
    EARTH_WARRIORS_CHAOS_TUNNELS(SlayerTask.EARTH_WARRIORS, "chaos_tunnels", "Chaos Tunnels", 3139, 5529, 0, "Earth warrior"),
    OTHERWORLDLY_BEINGS_ZANARIS(SlayerTask.OTHERWORLDLY_BEINGS, "zanaris", "Zanaris", 2381, 4422, 0, "Otherworldly being"),
    ELVES_HEART_OF_GIELINOR(SlayerTask.ELVES, "heart_of_gielinor", "Heart of Gielinor", 3221, 6909, 0, "Seren archer"),
    ELVES_PRIFDDINAS(SlayerTask.ELVES, "prifddinas", "Prifddinas", 2246, 3331, 0, "Cadarn magus"),
    ELVES_ELF_CAMP(SlayerTask.ELVES, "elf_camp", "Elf Camp", 2188, 3242, 0, "Elf warrior"),
    ELVES_ARANDAR(SlayerTask.ELVES, "arandar", "Arandar", 2382, 3334, 0, "Elf warrior"),
    ELVES_LLETYA(SlayerTask.ELVES, "lletya", "Lletya", 2328, 3172, 0, "Elf warrior"),
    DWARVES_DWARVEN_MINES(SlayerTask.DWARVES, "dwarven_mines", "Dwarven mines", 2984, 9807, 0, "Dwarf"),
    DWARVES_ICE_MOUNTAIN(SlayerTask.DWARVES, "ice_mountain", "Ice Mountain", 3000, 3445, 0, "Dwarf"),
    DWARVES_DWARVEN_MINE_RESOURCE_DUNGEON(SlayerTask.DWARVES, "dwarven_mine_resource_dungeon", "Dwarven Mine resource dungeon", 1048, 4572, 0, "Dwarf"),
    DWARVES_BLACK_KNIGHTS_BASE(SlayerTask.DWARVES, "black_knights_base", "Black Knights' Base", 2930, 9699, 0, "Dwarf"),
    DWARVES_KELDAGRIM(SlayerTask.DWARVES, "keldagrim", "Keldagrim", 10, 104, 0, "Dwarf"),
    DWARVES_MINING_GUILD(SlayerTask.DWARVES, "mining_guild", "Mining Guild", 3012, 3337, 0, "Dwarf"),
    DWARVES_WHITE_WOLF_MOUNTAIN(SlayerTask.DWARVES, "white_wolf_mountain", "White Wolf Mountain", 44, 18, 0, "Dwarf"),
    DWARVES_YANILLE(SlayerTask.DWARVES, "yanille", "Yanille", 2596, 3056, 0, "Dwarf"),
    BRONZE_DRAGONS_CHAOS_TUNNELS(SlayerTask.BRONZE_DRAGONS, "chaos_tunnels", "Chaos Tunnels", 3141, 5513, 0, "Bronze dragon"),
    BRONZE_DRAGONS_BRIMHAVEN_DUNGEON(SlayerTask.BRONZE_DRAGONS, "brimhaven_dungeon", "Brimhaven Dungeon", 171, 74, 0, "Bronze dragon"),
    IRON_DRAGONS_GHORROCK(SlayerTask.IRON_DRAGONS, "ghorrock", "Ghorrock", 2891, 3919, 0, "Iron dragon"),
    IRON_DRAGONS_BRIMHAVEN_DUNGEON_RESOURCE_DUNGEON(SlayerTask.IRON_DRAGONS, "brimhaven_dungeon_resource_dungeon", "Brimhaven Dungeon resource dungeon", 1121, 4527, 0, "Iron dragon"),
    IRON_DRAGONS_BRIMHAVEN_DUNGEON(SlayerTask.IRON_DRAGONS, "brimhaven_dungeon", "Brimhaven Dungeon", 144, 23, 0, "Iron dragon"),
    IRON_DRAGONS_KURADAL_S_DUNGEON(SlayerTask.IRON_DRAGONS, "kuradal_s_dungeon", "Kuradal's Dungeon", 109, 66, 0, "Iron dragon"),
    STEEL_DRAGONS_GHORROCK(SlayerTask.STEEL_DRAGONS, "ghorrock", "Ghorrock", 2893, 3929, 0, "Steel dragon"),
    STEEL_DRAGONS_BRIMHAVEN_DUNGEON_RESOURCE_DUNGEON(SlayerTask.STEEL_DRAGONS, "brimhaven_dungeon_resource_dungeon", "Brimhaven Dungeon resource dungeon", 1095, 4506, 0, "Steel dragon"),
    STEEL_DRAGONS_BRIMHAVEN_DUNGEON(SlayerTask.STEEL_DRAGONS, "brimhaven_dungeon", "Brimhaven Dungeon", 142, 37, 0, "Steel dragon"),
    STEEL_DRAGONS_KURADAL_S_DUNGEON(SlayerTask.STEEL_DRAGONS, "kuradal_s_dungeon", "Kuradal's Dungeon", 88, 76, 0, "Steel dragon"),
    WALL_BEASTS_LUMBRIDGE_SWAMP_CAVES(SlayerTask.WALL_BEASTS, "lumbridge_swamp_caves", "Lumbridge Swamp Caves", 3162, 9573, 0, "Wall beast"),
    CAVE_SLIMES_LUMBRIDGE_SWAMP_CAVES(SlayerTask.CAVE_SLIMES, "lumbridge_swamp_caves", "Lumbridge Swamp Caves", 3150, 9555, 0, "Cave slime"),
    CAVE_SLIMES_DORGESH_KAAN_SOUTH_DUNGEON(SlayerTask.CAVE_SLIMES, "dorgesh_kaan_south_dungeon", "Dorgesh-Kaan South Dungeon", 2696, 5232, 0, "Cave slime"),
    CAVE_BUGS_CHAOS_TUNNELS(SlayerTask.CAVE_BUGS, "chaos_tunnels", "Chaos Tunnels", 3268, 5553, 0, "Cave bug"),
    CAVE_BUGS_LUMBRIDGE_SWAMP_CAVES(SlayerTask.CAVE_BUGS, "lumbridge_swamp_caves", "Lumbridge Swamp Caves", 3148, 9578, 0, "Cave bug"),
    CAVE_BUGS_DORGESH_KAAN_SOUTH_DUNGEON(SlayerTask.CAVE_BUGS, "dorgesh_kaan_south_dungeon", "Dorgesh-Kaan South Dungeon", 2697, 5221, 0, "Cave bug"),
    CAVE_BUGS_BURTHORPE_SLAYER_CAVE(SlayerTask.CAVE_BUGS, "burthorpe_slayer_cave", "Burthorpe Slayer Cave", 224, 69, 0, "Cave bug"),
    CROCODILES_SOPHANEM(SlayerTask.CROCODILES, "sophanem", "Sophanem", 3251, 2837, 0, "Crocodile"),
    DARK_BEASTS_MOURNER_TUNNELS(SlayerTask.DARK_BEASTS, "mourner_tunnels", "Mourner tunnels", 1988, 4659, 0, "Dark beast"),
    DARK_BEASTS_MORYTANIA_SLAYER_TOWER_DUNGEON(SlayerTask.DARK_BEASTS, "morytania_slayer_tower_dungeon", "Morytania Slayer Tower dungeon", 1163, 4643, 0, "Dark beast"),
    DARK_BEASTS_THE_FORGOTTEN_CEMETERY(SlayerTask.DARK_BEASTS, "the_forgotten_cemetery", "The Forgotten Cemetery", 3012, 3769, 0, "Dark beast"),
    DARK_BEASTS_FORINTHRY_DUNGEON(SlayerTask.DARK_BEASTS, "forinthry_dungeon", "Forinthry Dungeon", 3020, 10140, 0, "Dark beast"),
    DARK_BEASTS_KURADAL_S_DUNGEON(SlayerTask.DARK_BEASTS, "kuradal_s_dungeon", "Kuradal's Dungeon", 112, 88, 0, "Dark beast"),
    DESERT_LIZARDS_NARDAH(SlayerTask.DESERT_LIZARDS, "nardah", "Nardah", 3384, 3015, 0, "Desert lizard"),
    FEVER_SPIDERS_BRAINDEATH_ISLAND(SlayerTask.FEVER_SPIDERS, "braindeath_island", "Braindeath Island", 2140, 5093, 0, "Fever spider"),
    HARPIE_BUG_SWARMS_KARAMJA(SlayerTask.HARPIE_BUG_SWARMS, "karamja", "Karamja", 2854, 3106, 0, "Harpie Bug Swarm"),
    SEA_SNAKES_MISCELLANIA_AND_ETCETERIA_DUNGEON(SlayerTask.SEA_SNAKES, "miscellania_and_etceteria_dungeon", "Miscellania and Etceteria dungeon", 2577, 10295, 0, "Sea Snake Hatchling"),
    SKELETAL_WYVERNS_ASGARNIAN_ICE_DUNGEON(SlayerTask.SKELETAL_WYVERNS, "asgarnian_ice_dungeon", "Asgarnian Ice Dungeon", 3025, 9543, 0, "Skeletal Wyvern"),
    KILLERWATTS_KILLERWATT_PLANE(SlayerTask.KILLERWATTS, "killerwatt_plane", "Killerwatt plane", 2642, 5202, 0, "Killerwatt"),
    MUTATED_ZYGOMITES_ZANARIS(SlayerTask.MUTATED_ZYGOMITES, "zanaris", "Zanaris", 2412, 4470, 0, "Mutated zygomite"),
    ICEFIENDS_GHORROCK(SlayerTask.ICEFIENDS, "ghorrock", "Ghorrock", 2893, 10385, 1, "Icefiend"),
    ICEFIENDS_ICE_MOUNTAIN(SlayerTask.ICEFIENDS, "ice_mountain", "Ice Mountain", 2995, 3468, 0, "Icefiend"),
    ICEFIENDS_GOD_WARS_DUNGEON(SlayerTask.ICEFIENDS, "god_wars_dungeon", "God Wars Dungeon", 2854, 5304, 0, "Icefiend"),
    ANKOU_WILDERNESS_CRATER(SlayerTask.ANKOU, "wilderness_crater", "Wilderness Crater", 3139, 3747, 0, "Ankou"),
    ANKOU_STRONGHOLD_OF_SECURITY(SlayerTask.ANKOU, "stronghold_of_security", "Stronghold of Security", 107, 45, 0, "Ankou"),
    CAVE_HORRORS_MOS_LE_HARMLESS_CAVES(SlayerTask.CAVE_HORRORS, "mos_le_harmless_caves", "Mos Le'Harmless Caves", 3720, 9349, 0, "Cave horror"),
    JUNGLE_HORRORS_MOS_LE_HARMLESS(SlayerTask.JUNGLE_HORRORS, "mos_le_harmless", "Mos Le'Harmless", 3670, 3021, 0, "Jungle horror"),
    GORAKS_GORAK_PLANE(SlayerTask.GORAKS, "gorak_plane", "Gorak Plane", 3023, 5339, 0, "Gorak"),
    SUQAHS_LUNAR_ISLE(SlayerTask.SUQAHS, "lunar_isle", "Lunar Isle", 2125, 3950, 0, "Suqah"),
    SUQAHS_LADY_ZAY(SlayerTask.SUQAHS, "lady_zay", "Lady Zay", 2142, 3900, 0, "Suqah"),
    BRINE_RATS_BRINE_RAT_CAVERN(SlayerTask.BRINE_RATS, "brine_rat_cavern", "Brine Rat Cavern", 2702, 10135, 0, "Brine rat"),
    SCABARITES_SCABARAS_DUNGEON(SlayerTask.SCABARITES, "scabaras_dungeon", "Scabaras Dungeon", 3361, 9238, 0, "Scabaras lancer"),
    SCABARITES_ULLEK(SlayerTask.SCABARITES, "ullek", "Ullek", 3435, 2808, 0, "Scabaras lancer"),
    MOLANISKS_DORGESH_KAAN_SOUTH_DUNGEON(SlayerTask.MOLANISKS, "dorgesh_kaan_south_dungeon", "Dorgesh-Kaan South Dungeon", 2727, 5234, 0, "Molanisk"),
    WATERFIENDS_GHORROCK(SlayerTask.WATERFIENDS, "ghorrock", "Ghorrock", 2901, 10352, 1, "Waterfiend"),
    WATERFIENDS_ANCIENT_CAVERN(SlayerTask.WATERFIENDS, "ancient_cavern", "Ancient Cavern", 1738, 5343, 0, "Waterfiend"),
    WATERFIENDS_BONEYARD(SlayerTask.WATERFIENDS, "boneyard", "Boneyard", 3362, 3642, 0, "Waterfiend"),
    WATERFIENDS_CHAOS_TUNNELS(SlayerTask.WATERFIENDS, "chaos_tunnels", "Chaos Tunnels", 3173, 5543, 0, "Waterfiend"),
    SPIRITUAL_WARRIORS_GOD_WARS_DUNGEON(SlayerTask.SPIRITUAL_WARRIORS, "god_wars_dungeon", "God Wars Dungeon", 2837, 5287, 0, "Spiritual warrior"),
    SPIRITUAL_RANGERS_GOD_WARS_DUNGEON(SlayerTask.SPIRITUAL_RANGERS, "god_wars_dungeon", "God Wars Dungeon", 2843, 5266, 0, "Spiritual ranger"),
    SPIRITUAL_MAGES_GOD_WARS_DUNGEON(SlayerTask.SPIRITUAL_MAGES, "god_wars_dungeon", "God Wars Dungeon", 2837, 5265, 0, "Spiritual mage"),
    WARPED_TORTOISES_POISON_WASTE_SLAYER_DUNGEON(SlayerTask.WARPED_TORTOISES, "poison_waste_slayer_dungeon", "Poison Waste Slayer Dungeon", 2039, 4178, 0, "Warped tortoise"),
    WARPED_TERRORBIRDS_POISON_WASTE_SLAYER_DUNGEON(SlayerTask.WARPED_TERRORBIRDS, "poison_waste_slayer_dungeon", "Poison Waste Slayer Dungeon", 1999, 4217, 0, "Warped terrorbird"),
    MITHRIL_DRAGONS_BRIMHAVEN_DUNGEON_RESOURCE_DUNGEON(SlayerTask.MITHRIL_DRAGONS, "brimhaven_dungeon_resource_dungeon", "Brimhaven Dungeon resource dungeon", 1091, 4528, 0, "Mithril dragon"),
    MITHRIL_DRAGONS_ANCIENT_CAVERN(SlayerTask.MITHRIL_DRAGONS, "ancient_cavern", "Ancient Cavern", 155, 78, 0, "Mithril dragon"),
    AQUANITES_FREMENNIK_SLAYER_DUNGEON(SlayerTask.AQUANITES, "fremennik_slayer_dungeon", "Fremennik Slayer Dungeon", 2710, 9971, 0, "Aquanite"),
    GANODERMIC_CREATURES_POLYPORE_DUNGEON(SlayerTask.GANODERMIC_CREATURES, "polypore_dungeon", "Polypore Dungeon", 3218, 9115, 0, "Ganodermic beast"),
    GANODERMIC_CREATURES_POLYPORE_DUNGEON_RESOURCE_DUNGEON(SlayerTask.GANODERMIC_CREATURES, "polypore_dungeon_resource_dungeon", "Polypore Dungeon resource dungeon", 3145, 9162, 0, "Ganodermic beast"),
    GRIFOLAPINES_POLYPORE_DUNGEON(SlayerTask.GRIFOLAPINES, "polypore_dungeon", "Polypore Dungeon", 3279, 9340, 0, "Grifolapine"),
    GRIFOLAPINES_POLYPORE_DUNGEON_RESOURCE_DUNGEON(SlayerTask.GRIFOLAPINES, "polypore_dungeon_resource_dungeon", "Polypore Dungeon resource dungeon", 3208, 9358, 0, "Grifolapine"),
    GRIFOLAROOS_POLYPORE_DUNGEON(SlayerTask.GRIFOLAROOS, "polypore_dungeon", "Polypore Dungeon", 3307, 9333, 0, "Grifolaroo"),
    GRIFOLAROOS_POLYPORE_DUNGEON_RESOURCE_DUNGEON(SlayerTask.GRIFOLAROOS, "polypore_dungeon_resource_dungeon", "Polypore Dungeon resource dungeon", 3247, 9321, 0, "Grifolaroo"),
    FUNGAL_MAGI_POLYPORE_DUNGEON(SlayerTask.FUNGAL_MAGI, "polypore_dungeon", "Polypore Dungeon", 3281, 9295, 0, "Fungal mage"),
    FUNGAL_MAGI_POLYPORE_DUNGEON_RESOURCE_DUNGEON(SlayerTask.FUNGAL_MAGI, "polypore_dungeon_resource_dungeon", "Polypore Dungeon resource dungeon", 3273, 9555, 0, "Fungal mage"),
    POLYPORE_CREATURES_POLYPORE_DUNGEON(SlayerTask.POLYPORE_CREATURES, "polypore_dungeon", "Polypore Dungeon", 3281, 9295, 0, "Fungal mage"),
    POLYPORE_CREATURES_POLYPORE_DUNGEON_RESOURCE_DUNGEON(SlayerTask.POLYPORE_CREATURES, "polypore_dungeon_resource_dungeon", "Polypore Dungeon resource dungeon", 3273, 9555, 0, "Fungal mage"),
    TZHAAR_TZHAAR_CITY(SlayerTask.TZHAAR, "tzhaar_city", "TzHaar City", 4622, 5121, 0, "TzHaar-Hur"),
    JUNGLE_STRYKEWYRMS_FELDIP_HILLS(SlayerTask.JUNGLE_STRYKEWYRMS, "feldip_hills", "Feldip Hills", 2445, 2896, 0, "Jungle strykewyrm"),
    DESERT_STRYKEWYRMS_AL_KHARID(SlayerTask.DESERT_STRYKEWYRMS, "al_kharid", "Al Kharid", 3363, 3155, 0, "Desert strykewyrm"),
    ICE_STRYKEWYRMS_ICE_STRYKEWYRM_CAVE(SlayerTask.ICE_STRYKEWYRMS, "ice_strykewyrm_cave", "Ice strykewyrm cave", 3412, 5675, 0, "Ice strykewyrm"),
    ICE_STRYKEWYRMS_FROZEN_WASTE_PLATEAU(SlayerTask.ICE_STRYKEWYRMS, "frozen_waste_plateau", "Frozen Waste Plateau", 2972, 3851, 0, "Ice strykewyrm"),
    ICE_STRYKEWYRMS_LAVA_MAZE(SlayerTask.ICE_STRYKEWYRMS, "lava_maze", "Lava Maze", 3055, 3792, 0, "Ice strykewyrm"),
    LIVING_ROCK_CREATURES_LIVING_ROCK_CAVERNS(SlayerTask.LIVING_ROCK_CREATURES, "living_rock_caverns", "Living Rock Caverns", 3610, 5111, 0, "Living rock protector"),
    CYCLOPES_GOD_WARS_DUNGEON(SlayerTask.CYCLOPES, "god_wars_dungeon", "God Wars Dungeon", 2832, 5325, 0, "Cyclops"),
    CYCLOPES_WARRIORS_GUILD(SlayerTask.CYCLOPES, "warriors_guild", "Warriors' Guild", 2842, 3546, 2, "Cyclops"),
    CYCLOPES_CYCLOPS_LABOURER(SlayerTask.CYCLOPES, "cyclops_labourer", "Cyclops labourer", 2068, 11344, 0),
    MUTATED_JADINKOS_JADINKO_LAIR(SlayerTask.MUTATED_JADINKOS, "jadinko_lair", "Jadinko lair", 3013, 9261, 0, "Mutated jadinko baby"),
    MUTATED_JADINKOS_JADINKO_LAIR_2(SlayerTask.MUTATED_JADINKOS, "jadinko_lair_2", "Jadinko Lair", 3054, 9237, 0, "Mutated jadinko male"),
    VYREWATCH_MEIYERDITCH(SlayerTask.VYREWATCH, "meiyerditch", "Meiyerditch", 3597, 3193, 0, "Vyrewatch"),
    VYREWATCH_DARKMEYER(SlayerTask.VYREWATCH, "darkmeyer", "Darkmeyer", 3641, 3344, 0, "Vyrewatch"),
    VYREWATCH_BURGH_DE_ROTT_WOODS(SlayerTask.VYREWATCH, "burgh_de_rott_woods", "Burgh de Rott Woods", 3553, 3193, 0, "Vyrewatch"),
    VYREWATCH_CASTLE_DRAKAN(SlayerTask.VYREWATCH, "castle_drakan", "Castle Drakan", 3526, 3351, 0, "Vyrewatch"),
    GELATINOUS_ABOMINATIONS_BURTHORPE_SLAYER_CAVE(SlayerTask.GELATINOUS_ABOMINATIONS, "burthorpe_slayer_cave", "Burthorpe Slayer Cave", 2215, 4513, 0, "Gelatinous abomination"),
    GROTWORMS_GROTWORM_LAIR(SlayerTask.GROTWORMS, "grotworm_lair", "Grotworm Lair", 1172, 6368, 0, "Young grotworm"),
    CRESS_CREATIONS_TOLNA_S_RIFT(SlayerTask.CRESS_CREATIONS, "tolna_s_rift", "Tolna's rift", 3269, 9798, 0, "Hopeless creature"),
    CRESS_CREATIONS_SOUL_WARS(SlayerTask.CRESS_CREATIONS, "soul_wars", "Soul Wars", 2125, 2888, 0, "Avatar of Creation"),
    CRESS_CREATIONS_TREE_GNOME_VILLAGE_LOCATION(SlayerTask.CRESS_CREATIONS, "tree_gnome_village_location", "Tree Gnome Village (location)", 2542, 3170, 0, "Evil creature"),
    AVIANSIES_GOD_WARS_DUNGEON(SlayerTask.AVIANSIES, "god_wars_dungeon", "God Wars Dungeon", 2834, 5283, 0, "Aviansie"),
    ASCENSION_MEMBERS_MONASTERY_OF_ASCENSION(SlayerTask.ASCENSION_MEMBERS, "monastery_of_ascension", "Monastery of Ascension", 1039, 671, 0, "Capsarius"),
    PIGS_PIG_PITS_LOCATIONS(SlayerTask.PIGS, "pig_pits_locations", "Pig Pits#Locations", 1046, 5661, 0, "Pig"),
    PIGS_FALADOR_FARM(SlayerTask.PIGS, "falador_farm", "Falador Farm", 1045, 5720, 0, "Pig"),
    PIGS_PIG_PITS_LOCATIONS_2(SlayerTask.PIGS, "pig_pits_locations_2", "Pig_Pits#Locations", 1048, 5790, 0, "Pig"),
    AIRUT_MAZCAB(SlayerTask.AIRUT, "mazcab", "Mazcab", 4235, 766, 0, "Airut"),
    AIRUT_PISCATORIS_PENINSULA(SlayerTask.AIRUT, "piscatoris_peninsula", "Piscatoris Peninsula", 2262, 3611, 0, "Airut"),
    AIRUT_KURADAL_S_DUNGEON(SlayerTask.AIRUT, "kuradal_s_dungeon", "Kuradal's Dungeon", 119, 108, 0, "Airut"),
    CELESTIAL_DRAGONS_DRAGONTOOTH_ISLAND_RESOURCE_DUNGEON(SlayerTask.CELESTIAL_DRAGONS, "dragontooth_island_resource_dungeon", "Dragontooth Island resource dungeon", 2247, 5978, 0, "Celestial dragon"),
    GLACORS_GLACOR_CAVE(SlayerTask.GLACORS, "glacor_cave", "Glacor Cave", 4169, 5724, 0, "Glacor"),
    GLACORS_ELDER_GOD_WARS_DUNGEON(SlayerTask.GLACORS, "elder_god_wars_dungeon", "Elder God Wars Dungeon", 1759, 1127, 0, "Glacor"),
    GLACORS_GLACOR(SlayerTask.GLACORS, "glacor", "Glacor", 1756, 1161, 0, "Glacor"),
    TORMENTED_DEMONS_ANCIENT_GUTHIX_TEMPLE(SlayerTask.TORMENTED_DEMONS, "ancient_guthix_temple", "Ancient Guthix Temple", 2589, 5714, 0, "Tormented demon"),
    EDIMMU_EDIMMU_RESOURCE_DUNGEON(SlayerTask.EDIMMU, "edimmu_resource_dungeon", "Edimmu resource dungeon", 1352, 4647, 0, "Edimmu"),
    SHADOW_CREATURES_TEMPLE_OF_LIGHT(SlayerTask.SHADOW_CREATURES, "temple_of_light", "Temple of Light", 1859, 4659, 0, "Shadow"),
    SHADOW_CREATURES_SHADOW_DUNGEON(SlayerTask.SHADOW_CREATURES, "shadow_dungeon", "Shadow Dungeon", 2626, 5065, 0, "Giant skeleton"),
    SHADOW_CREATURES_CHAOS_TUNNELS(SlayerTask.SHADOW_CREATURES, "chaos_tunnels", "Chaos Tunnels", 3283, 5510, 0, "Shadow Hound"),
    LAVA_STRYKEWYRMS_LAVA_MAZE(SlayerTask.LAVA_STRYKEWYRMS, "lava_maze", "Lava Maze", 3022, 3822, 0, "Lava strykewyrm"),
    ADAMANT_DRAGONS_ADAMANT_DRAGON_DUNGEON(SlayerTask.ADAMANT_DRAGONS, "adamant_dragon_dungeon", "Adamant dragon dungeon", 4486, 6037, 0, "Adamant dragon"),
    ADAMANT_DRAGONS_DRAGONKIN_LAIR(SlayerTask.ADAMANT_DRAGONS, "dragonkin_lair", "Dragonkin Lair", 1247, 4172, 0, "Adamant dragon"),
    RUNE_DRAGONS_MOUNT_FIREWAKE(SlayerTask.RUNE_DRAGONS, "mount_firewake", "Mount Firewake", 4741, 6043, 0, "Rune dragon"),
    CRYSTAL_SHAPESHIFTERS_TARDDIAD(SlayerTask.CRYSTAL_SHAPESHIFTERS, "tarddiad", "Tarddiad", 4054, 6613, 0, "Crystal Shapeshifter"),
    LIVING_WYVERNS_ASGARNIAN_ICE_DUNGEON(SlayerTask.LIVING_WYVERNS, "asgarnian_ice_dungeon", "Asgarnian Ice Dungeon", 5131, 7505, 0, "Wyvern"),
    LIVING_WYVERNS_FROZEN_WASTE_PLATEAU(SlayerTask.LIVING_WYVERNS, "frozen_waste_plateau", "Frozen Waste Plateau", 2960, 3889, 0, "Wyvern"),
    RIPPER_DEMONS_DEMONIC_RUINS(SlayerTask.RIPPER_DEMONS, "demonic_ruins", "Demonic Ruins", 3223, 3867, 0, "Ripper Demon"),
    RIPPER_DEMONS_RIPPER_DEMON_CAVE(SlayerTask.RIPPER_DEMONS, "ripper_demon_cave", "Ripper Demon cave", 5140, 7584, 0, "Ripper Demon"),
    RIPPER_DEMONS_LAVA_MAZE_DUNGEON(SlayerTask.RIPPER_DEMONS, "lava_maze_dungeon", "Lava Maze Dungeon", 3029, 10250, 0, "Ripper Demon"),
    RIPPER_DEMONS_LAVA_MAZE(SlayerTask.RIPPER_DEMONS, "lava_maze", "Lava Maze", 3082, 3860, 0, "Ripper Demon"),
    RIPPER_DEMONS_MAGE_ARENA(SlayerTask.RIPPER_DEMONS, "mage_arena", "Mage Arena", 3106, 3906, 0, "Ripper Demon"),
    CAMEL_WARRIORS_CAMEL_WARRIORS_ISLAND(SlayerTask.CAMEL_WARRIORS, "camel_warriors_island", "Camel Warriors island", 3350, 2728, 0, "Camel Warrior"),
    ACHERON_MAMMOTHS_MAMMOTH_ICEBERG(SlayerTask.ACHERON_MAMMOTHS, "mammoth_iceberg", "Mammoth iceberg", 2465, 4013, 1, "Acheron mammoth"),
    ACHERON_MAMMOTHS_FROZEN_WASTE_PLATEAU(SlayerTask.ACHERON_MAMMOTHS, "frozen_waste_plateau", "Frozen Waste Plateau", 2981, 3957, 0, "Acheron mammoth"),
    CHAOS_GIANTS_BARENDIR(SlayerTask.CHAOS_GIANTS, "barendir", "Barendir", 1941, 6249, 0, "Chaos Giant"),
    NIGHTMARE_CREATURES_FRENESKAE(SlayerTask.NIGHTMARE_CREATURES, "freneskae", "Freneskae", 2205, 12507, 1, "Nightmare"),
    ONYX_DRAGONS_WILDERNESS(SlayerTask.ONYX_DRAGONS, "wilderness", "Wilderness", 3236, 3780, 0, "Onyx dragon"),
    ONYX_DRAGONS_GEMSTONE_CAVERN(SlayerTask.ONYX_DRAGONS, "gemstone_cavern", "Gemstone cavern", 2959, 9048, 0, "Onyx dragon"),
    ONYX_DRAGONS_DEEP_WILDERNESS_DUNGEON(SlayerTask.ONYX_DRAGONS, "deep_wilderness_dungeon", "Deep Wilderness Dungeon", 3018, 10323, 0, "Onyx dragon"),
    HYDRIX_DRAGONS_GEMSTONE_CAVERN(SlayerTask.HYDRIX_DRAGONS, "gemstone_cavern", "Gemstone cavern", 3010, 9019, 0, "Hydrix dragon"),
    HYDRIX_DRAGONS_WILDERNESS_LEVEL_47_LAVA_MAZE_MINE(SlayerTask.HYDRIX_DRAGONS, "wilderness_level_47_lava_maze_mine", "Wilderness (level 47) Lava Maze mine", 3012, 3896, 0, "Hydrix dragon"),
    HYDRIX_DRAGONS_DEEP_WILDERNESS_DUNGEON(SlayerTask.HYDRIX_DRAGONS, "deep_wilderness_dungeon", "Deep Wilderness Dungeon", 3030, 10342, 0, "Hydrix dragon"),
    GEMSTONE_DRAGONS_GEMSTONE_CAVERN(SlayerTask.GEMSTONE_DRAGONS, "gemstone_cavern", "Gemstone cavern", 2959, 8995, 0, "Dragonstone dragon"),
    GEMSTONE_DRAGONS_DEEP_WILDERNESS_DUNGEON(SlayerTask.GEMSTONE_DRAGONS, "deep_wilderness_dungeon", "Deep Wilderness Dungeon", 3033, 10313, 0, "Dragonstone dragon"),
    CORRUPTED_SCORPIONS_SOPHANEM_SLAYER_DUNGEON(SlayerTask.CORRUPTED_SCORPIONS, "sophanem_slayer_dungeon", "Sophanem Slayer Dungeon", 3270, 9113, 0, "Corrupted scorpion"),
    CORRUPTED_SCARABS_SOPHANEM_SLAYER_DUNGEON(SlayerTask.CORRUPTED_SCARABS, "sophanem_slayer_dungeon", "Sophanem Slayer Dungeon", 3300, 9109, 0, "Corrupted scarab"),
    CORRUPTED_LIZARDS_SOPHANEM_SLAYER_DUNGEON(SlayerTask.CORRUPTED_LIZARDS, "sophanem_slayer_dungeon", "Sophanem Slayer Dungeon", 3292, 9141, 0, "Corrupted lizard"),
    CORRUPTED_DUST_DEVILS_SOPHANEM_SLAYER_DUNGEON(SlayerTask.CORRUPTED_DUST_DEVILS, "sophanem_slayer_dungeon", "Sophanem Slayer Dungeon", 3274, 9192, 0, "Corrupted dust devil"),
    CORRUPTED_KALPHITES_SOPHANEM_SLAYER_DUNGEON(SlayerTask.CORRUPTED_KALPHITES, "sophanem_slayer_dungeon", "Sophanem Slayer Dungeon", 3327, 9200, 0, "Corrupted kalphite guardian"),
    CORRUPTED_WORKER_SOPHANEM_SLAYER_DUNGEON(SlayerTask.CORRUPTED_WORKER, "sophanem_slayer_dungeon", "Sophanem Slayer Dungeon", 3364, 9174, 0, "Corrupted worker"),
    SALAWA_AKH_SOPHANEM_SLAYER_DUNGEON(SlayerTask.SALAWA_AKH, "sophanem_slayer_dungeon", "Sophanem Slayer Dungeon", 3327, 9169, 0, "Salawa akh"),
    FELINE_AKH_SOPHANEM_SLAYER_DUNGEON(SlayerTask.FELINE_AKH, "sophanem_slayer_dungeon", "Sophanem Slayer Dungeon", 3298, 9189, 0, "Feline akh"),
    GORILLA_AKH_SOPHANEM_SLAYER_DUNGEON(SlayerTask.GORILLA_AKH, "sophanem_slayer_dungeon", "Sophanem Slayer Dungeon", 3336, 9138, 0, "Gorilla akh"),
    CROCODILE_AKH_SOPHANEM_SLAYER_DUNGEON(SlayerTask.CROCODILE_AKH, "sophanem_slayer_dungeon", "Sophanem Slayer Dungeon", 3360, 9124, 0, "Crocodile akh"),
    SCARAB_AKH_SOPHANEM_SLAYER_DUNGEON(SlayerTask.SCARAB_AKH, "sophanem_slayer_dungeon", "Sophanem Slayer Dungeon", 3338, 9156, 0, "Scarab akh"),
    IMPERIAL_GUARD_AKH_SOPHANEM_SLAYER_DUNGEON(SlayerTask.IMPERIAL_GUARD_AKH, "sophanem_slayer_dungeon", "Sophanem Slayer Dungeon", 3351, 9065, 0, "Imperial mage akh"),
    CORRUPTED_CREATURES_SOPHANEM_SLAYER_DUNGEON(SlayerTask.CORRUPTED_CREATURES, "sophanem_slayer_dungeon", "Sophanem Slayer Dungeon", 3274, 9192, 0, "Corrupted dust devil"),
    SOUL_DEVOURERS_SOPHANEM_SLAYER_DUNGEON(SlayerTask.SOUL_DEVOURERS, "sophanem_slayer_dungeon", "Sophanem Slayer Dungeon", 3360, 9124, 0, "Crocodile akh"),
    CREATURES_OF_THE_LOST_GROVE_THE_LOST_GROVE(SlayerTask.CREATURES_OF_THE_LOST_GROVE, "the_lost_grove", "The Lost Grove", 1931, 3224, 0, "Bulbous crawler"),
    SOULGAZERS_STALKER_DUNGEON(SlayerTask.SOULGAZERS, "stalker_dungeon", "Stalker dungeon", 2253, 9260, 0, "Soulgazer"),
    SOULGAZERS_WILDERNESS(SlayerTask.SOULGAZERS, "wilderness", "Wilderness", 3332, 3722, 0, "Soulgazer"),
    STALKER_CREATURES_STALKER_DUNGEON(SlayerTask.STALKER_CREATURES, "stalker_dungeon", "Stalker dungeon", 2251, 9232, 0, "Seeker"),
    STALKER_CREATURES_WILDERNESS(SlayerTask.STALKER_CREATURES, "wilderness", "Wilderness", 3332, 3722, 0, "Soulgazer"),
    REVENANTS_FORINTHRY_DUNGEON(SlayerTask.REVENANTS, "forinthry_dungeon", "Forinthry Dungeon", 3110, 10139, 0, "Revenant cyclops"),
    FROGS_SOPHANEM(SlayerTask.FROGS, "sophanem", "Sophanem", 3276, 2760, 0, "Plague frog"),
    FROGS_DORGESH_KAAN_SOUTH_DUNGEON(SlayerTask.FROGS, "dorgesh_kaan_south_dungeon", "Dorgesh-Kaan South Dungeon", 2696, 5227, 0, "Big frog"),
    FROGS_LUMBRIDGE_SWAMP_CAVES(SlayerTask.FROGS, "lumbridge_swamp_caves", "Lumbridge Swamp Caves", 3151, 9550, 0, "Big frog"),
    DINOSAURS_ANACHRONIA(SlayerTask.DINOSAURS, "anachronia", "Anachronia", 4035, 4525, 0, "Brutish dinosaur"),
    VILE_BLOOMS_THE_LOST_GROVE(SlayerTask.VILE_BLOOMS, "the_lost_grove", "The Lost Grove", 1931, 3224, 0, "Bulbous crawler"),
    DRAGONS_ADAMANT_DRAGON_DUNGEON(SlayerTask.DRAGONS, "adamant_dragon_dungeon", "Adamant dragon dungeon", 4486, 6037, 0, "Adamant dragon"),
    DRAGONS_CHAOS_TUNNELS(SlayerTask.DRAGONS, "chaos_tunnels", "Chaos Tunnels", 3299, 5539, 0, "Baby black dragon"),
    DRAGONS_MOUNT_FIREWAKE(SlayerTask.DRAGONS, "mount_firewake", "Mount Firewake", 4741, 6043, 0, "Rune dragon"),
    DRAGONS_DRAGONKIN_LAIR(SlayerTask.DRAGONS, "dragonkin_lair", "Dragonkin Lair", 1247, 4172, 0, "Adamant dragon"),
    DRAGONS_EVIL_CHICKEN_S_LAIR(SlayerTask.DRAGONS, "evil_chicken_s_lair", "Evil Chicken's Lair", 1542, 4393, 0, "Baby black dragon"),
    DEMONS_WILDERNESS(SlayerTask.DEMONS, "wilderness", "Wilderness", 3212, 3662, 0, "Abyssal demon"),
    DEMONS_DEMONIC_RUINS(SlayerTask.DEMONS, "demonic_ruins", "Demonic Ruins", 3288, 3829, 0, "Black demon"),
    DEMONS_FORINTHRY_DUNGEON(SlayerTask.DEMONS, "forinthry_dungeon", "Forinthry Dungeon", 3083, 10082, 0, "Greater demon"),
    DEMONS_ABYSSAL_AREA(SlayerTask.DEMONS, "abyssal_area", "Abyssal Area", 3016, 4891, 0, "Abyssal demon"),
    DEMONS_BRIMHAVEN_DUNGEON(SlayerTask.DEMONS, "brimhaven_dungeon", "Brimhaven Dungeon", 140, 81, 0, "Black demon", "Greater demon"),
    DEMONS_CHAOS_TUNNELS(SlayerTask.DEMONS, "chaos_tunnels", "Chaos Tunnels", 3157, 5522, 0, "Black demon"),
    DEMONS_CHAOS_TUNNELS_RESOURCE_DUNGEON(SlayerTask.DEMONS, "chaos_tunnels_resource_dungeon", "Chaos Tunnels resource dungeon", 1232, 4513, 0, "Black demon"),
    DEMONS_EDGEVILLE_DUNGEON(SlayerTask.DEMONS, "edgeville_dungeon", "Edgeville Dungeon", 3085, 9958, 0, "Black demon"),
    DEMONS_ENTRANA_DUNGEON(SlayerTask.DEMONS, "entrana_dungeon", "Entrana Dungeon", 2861, 9747, 0, "Greater demon"),
    DEMONS_KURADAL_S_DUNGEON(SlayerTask.DEMONS, "kuradal_s_dungeon", "Kuradal's Dungeon", 94, 103, 0, "Abyssal demon", "Greater demon"),
    DEMONS_MORYTANIA_SLAYER_TOWER_DUNGEON(SlayerTask.DEMONS, "morytania_slayer_tower_dungeon", "Morytania Slayer Tower dungeon", 1165, 4618, 0, "Abyssal demon"),
    DEMONS_OGRE_ENCLAVE(SlayerTask.DEMONS, "ogre_enclave", "Ogre Enclave", 2586, 9458, 0, "Greater demon"),
    DEMONS_SLAYER_TOWER(SlayerTask.DEMONS, "slayer_tower", "Slayer Tower", 3402, 3545, 2, "Abyssal demon"),
    DEMONS_TAVERLEY_DUNGEON(SlayerTask.DEMONS, "taverley_dungeon", "Taverley Dungeon", 2854, 9776, 0, "Black demon"),
    DEMONS_WILDERNESS_CRATER(SlayerTask.DEMONS, "wilderness_crater", "Wilderness Crater", 3138, 3679, 0, "Greater demon"),
    CREATURES_OF_DAEMONHEIM_POISON_WASTE_SLAYER_DUNGEON(SlayerTask.CREATURES_OF_DAEMONHEIM, "poison_waste_slayer_dungeon", "Poison Waste Slayer Dungeon", 1999, 4217, 0, "Warped terrorbird"),
    CREATURES_OF_DAEMONHEIM_LUMBRIDGE_CATACOMBS(SlayerTask.CREATURES_OF_DAEMONHEIM, "lumbridge_catacombs", "Lumbridge Catacombs", 4013, 5511, 0, "Warped bat"),
    ZAROSIAN_CREATURES_HEART_OF_GIELINOR(SlayerTask.ZAROSIAN_CREATURES, "heart_of_gielinor", "Heart of Gielinor", 3138, 6903, 0, "Ancient mage"),
    ZAROSIAN_CREATURES_ANCIENT_PRISON(SlayerTask.ZAROSIAN_CREATURES, "ancient_prison", "Ancient Prison", 2864, 5210, 0, "Ancient mage"),
    STRYKEWYRMS_LAVA_MAZE(SlayerTask.STRYKEWYRMS, "lava_maze", "Lava Maze", 3055, 3792, 0, "Ice strykewyrm"),
    STRYKEWYRMS_AL_KHARID(SlayerTask.STRYKEWYRMS, "al_kharid", "Al Kharid", 3363, 3155, 0, "Desert strykewyrm"),
    STRYKEWYRMS_ICE_STRYKEWYRM_CAVE(SlayerTask.STRYKEWYRMS, "ice_strykewyrm_cave", "Ice strykewyrm cave", 3412, 5675, 0, "Ice strykewyrm"),
    STRYKEWYRMS_FROZEN_WASTE_PLATEAU(SlayerTask.STRYKEWYRMS, "frozen_waste_plateau", "Frozen Waste Plateau", 2972, 3851, 0, "Ice strykewyrm"),
    COCKROACHES_LUMBRIDGE_CATACOMBS(SlayerTask.COCKROACHES, "lumbridge_catacombs", "Lumbridge Catacombs", 3970, 5552, 0, "Warped cockroach"),
    COCKROACHES_STRONGHOLD_OF_PLAYER_SAFETY(SlayerTask.COCKROACHES, "stronghold_of_player_safety", "Stronghold of Player Safety", 3077, 3461, 0, "Cockroach drone"),
    NODON_DRAGONKIN_NODON_FRONT(SlayerTask.NODON_DRAGONKIN, "nodon_front", "Nodon Front", 1708, 1325, 0, "Nodon artificer"),
    ABYSSAL_DEMONS_180_WILDERNESS(SlayerTask.ABYSSAL_DEMONS_180, "wilderness", "Wilderness", 3212, 3662, 0, "Abyssal demon"),
    ABYSSAL_DEMONS_180_MORYTANIA_SLAYER_TOWER_DUNGEON(SlayerTask.ABYSSAL_DEMONS_180, "morytania_slayer_tower_dungeon", "Morytania Slayer Tower dungeon", 1165, 4618, 0, "Abyssal demon"),
    ABYSSAL_DEMONS_180_SLAYER_TOWER(SlayerTask.ABYSSAL_DEMONS_180, "slayer_tower", "Slayer Tower", 3402, 3545, 2, "Abyssal demon"),
    ABYSSAL_DEMONS_180_ABYSSAL_AREA(SlayerTask.ABYSSAL_DEMONS_180, "abyssal_area", "Abyssal Area", 3016, 4891, 0, "Abyssal demon"),
    ABYSSAL_DEMONS_180_KURADAL_S_DUNGEON(SlayerTask.ABYSSAL_DEMONS_180, "kuradal_s_dungeon", "Kuradal's Dungeon", 94, 103, 0, "Abyssal demon"),
    ABYSSAL_SAVAGES_ROGUES_CASTLE(SlayerTask.ABYSSAL_SAVAGES, "rogues_castle", "Rogues' Castle", 3222, 3929, 0, "Abyssal savage"),
    ABYSSAL_SAVAGES_SENNTISTEN_ASYLUM(SlayerTask.ABYSSAL_SAVAGES, "senntisten_asylum", "Senntisten Asylum", 1960, 1500, 0, "Abyssal savage"),
    ABYSSAL_SAVAGES_BANDIT_CAMP_WILDERNESS(SlayerTask.ABYSSAL_SAVAGES, "bandit_camp_wilderness", "Bandit Camp (Wilderness)", 3023, 3718, 0, "Abyssal savage"),
    ABYSSAL_SAVAGES_WILDERNESS_LEVEL_35_HOBGOBLIN_MINE(SlayerTask.ABYSSAL_SAVAGES, "wilderness_level_35_hobgoblin_mine", "Wilderness (level 35) hobgoblin mine", 3012, 3766, 0, "Abyssal savage"),
    ABYSSAL_BEASTS_LAVA_MAZE(SlayerTask.ABYSSAL_BEASTS, "lava_maze", "Lava Maze", 3088, 3810, 0, "Abyssal beast"),
    ABYSSAL_BEASTS_SENNTISTEN_ASYLUM(SlayerTask.ABYSSAL_BEASTS, "senntisten_asylum", "Senntisten Asylum", 1974, 1463, 0, "Abyssal beast"),
    ABYSSAL_BEASTS_WILDERNESS_LEVEL_35_HOBGOBLIN_MINE(SlayerTask.ABYSSAL_BEASTS, "wilderness_level_35_hobgoblin_mine", "Wilderness (level 35) hobgoblin mine", 3014, 3749, 0, "Abyssal beast"),
    ABYSSAL_LORDS_HERB_PATCH_WILDERNESS(SlayerTask.ABYSSAL_LORDS, "herb_patch_wilderness", "Herb patch (Wilderness)", 3148, 3883, 0, "Abyssal lord"),
    ABYSSAL_LORDS_SENNTISTEN_ASYLUM(SlayerTask.ABYSSAL_LORDS, "senntisten_asylum", "Senntisten Asylum", 1990, 1488, 0, "Abyssal lord"),
    GREATER_DEMON_BERSERKERS_AND_ASH_LORDS_WILDERNESS(SlayerTask.GREATER_DEMON_BERSERKERS_AND_ASH_LORDS, "wilderness", "Wilderness", 3335, 3815, 0, "Greater demon ash lord"),
    FETID_ZOMBIES_CRYPT_WILDERNESS(SlayerTask.FETID_ZOMBIES, "crypt_wilderness", "Crypt (Wilderness)", 3265, 3582, 0, "Fetid zombie"),
    RISEN_GHOSTS_CRYPT_WILDERNESS(SlayerTask.RISEN_GHOSTS, "crypt_wilderness", "Crypt (Wilderness)", 1950, 1587, 1, "Risen ghost"),
    ARMOURED_PHANTOMS_CRYPT_WILDERNESS(SlayerTask.ARMOURED_PHANTOMS, "crypt_wilderness", "Crypt (Wilderness)", 1928, 1577, 1, "Armoured phantom"),
    ZEMOUREGALS_UNDEAD_CRYPT_WILDERNESS(SlayerTask.ZEMOUREGALS_UNDEAD, "crypt_wilderness", "Crypt (Wilderness)", 1928, 1577, 1, "Armoured phantom"),
    PHANTOMS_CRYPT_WILDERNESS(SlayerTask.PHANTOMS, "crypt_wilderness", "Crypt (Wilderness)", 1928, 1577, 1, "Armoured phantom"),
    UNDEAD_NEW_VARROCK(SlayerTask.UNDEAD, "new_varrock", "New Varrock", 3696, 9022, 0, "Zombie"),
    UNDEAD_EDGEVILLE_DUNGEON(SlayerTask.UNDEAD, "edgeville_dungeon", "Edgeville Dungeon", 3094, 9889, 0, "Skeleton"),
    UNDEAD_CHAOS_TUNNELS(SlayerTask.UNDEAD, "chaos_tunnels", "Chaos Tunnels", 3168, 5493, 0, "Skeleton"),
    UNDEAD_ARDOUGNE_SEWERS(SlayerTask.UNDEAD, "ardougne_sewers", "Ardougne Sewers", 2675, 9680, 0, "Zombie"),
    UNDEAD_CRANDOR(SlayerTask.UNDEAD, "crandor", "Crandor", 2820, 3259, 0, "Skeleton"),
    UNDEAD_CRANDOR_AND_KARAMJA_DUNGEON(SlayerTask.UNDEAD, "crandor_and_karamja_dungeon", "Crandor and Karamja Dungeon", 288, 173, 0, "Skeleton"),
    UNDEAD_DRAYNOR_SEWERS(SlayerTask.UNDEAD, "draynor_sewers", "Draynor Sewers", 3119, 9647, 0, "Zombie", "Skeleton"),
    UNDEAD_GLARIAL_S_TOMB(SlayerTask.UNDEAD, "glarial_s_tomb", "Glarial's Tomb", 2533, 9842, 0, "Zombie", "Skeleton"),
    UNDEAD_GNOME_VILLAGE_DUNGEON(SlayerTask.UNDEAD, "gnome_village_dungeon", "Gnome Village Dungeon", 2603, 4446, 0, "Zombie"),
    UNDEAD_OGRE_ENCLAVE(SlayerTask.UNDEAD, "ogre_enclave", "Ogre Enclave", 2576, 9436, 0, "Skeleton"),
    UNDEAD_SENNTISTEN_TEMPLE(SlayerTask.UNDEAD, "senntisten_temple", "Senntisten Temple", 3142, 5708, 0, "Skeleton"),
    UNDEAD_STRONGHOLD_OF_SECURITY_SEPULCHRE_OF_DEATH_4TH_LEVEL(SlayerTask.UNDEAD, "stronghold_of_security_sepulchre_of_death_4th_level", "Stronghold of Security#Sepulchre of Death (4th level)", 101, 3, 0, "Skeleton"),
    UNDEAD_TAVERLEY_DUNGEON(SlayerTask.UNDEAD, "taverley_dungeon", "Taverley Dungeon", 2882, 9826, 0, "Skeleton"),
    UNDEAD_TEMPLE_OF_IKOV_DUNGEON(SlayerTask.UNDEAD, "temple_of_ikov_dungeon", "Temple of Ikov (dungeon)", 2658, 9820, 0, "Skeleton"),
    UNDEAD_UNDERGROUND_PASS(SlayerTask.UNDEAD, "underground_pass", "Underground Pass", 2394, 9707, 0, "Zombie"),
    UNDEAD_UNDERGROUND_PASS_DUNGEON(SlayerTask.UNDEAD, "underground_pass_dungeon", "Underground Pass (dungeon)", 2371, 9611, 0, "Skeleton"),
    UNDEAD_VARROCK_SEWERS(SlayerTask.UNDEAD, "varrock_sewers", "Varrock Sewers", 3119, 9862, 0, "Zombie", "Skeleton"),
    UNDEAD_WATERFALL_DUNGEON(SlayerTask.UNDEAD, "waterfall_dungeon", "Waterfall Dungeon", 2586, 9884, 0, "Skeleton"),
    UNDEAD_WEST_ARDOUGNE(SlayerTask.UNDEAD, "west_ardougne", "West Ardougne", 2497, 3292, 0, "Zombie"),
    UNDEAD_WILDERNESS(SlayerTask.UNDEAD, "wilderness", "Wilderness", 3072, 3531, 0, "Skeleton"),
    UNDEAD_WILDERNESS_LEVEL_9_SOUTH_WEST_MINE(SlayerTask.UNDEAD, "wilderness_level_9_south_west_mine", "Wilderness (level 9) south-west mine", 3008, 3595, 0, "Skeleton"),
    UNDEAD_WILDERNESS_AGILITY_COURSE_PIT(SlayerTask.UNDEAD, "wilderness_agility_course_pit", "Wilderness Agility Course Pit", 2994, 10346, 0, "Skeleton"),
    UNDEAD_WILDERNESS_CRATER(SlayerTask.UNDEAD, "wilderness_crater", "Wilderness Crater", 3092, 3717, 0, "Skeleton"),
    UNDEAD_WIZARDS_GUILD(SlayerTask.UNDEAD, "wizards_guild", "Wizards' Guild", 87, 85, 0, "Zombie"),
    UNDEAD_YANILLE_AGILITY_DUNGEON(SlayerTask.UNDEAD, "yanille_agility_dungeon", "Yanille Agility dungeon", 66, 98, 0, "Skeleton"),
    PROFANE_SCABARITES_SCABARITE_CAVERN(SlayerTask.PROFANE_SCABARITES, "scabarite_cavern", "Scabarite Cavern", 3268, 7596, 0, "Profane Scabarite"),
    BEASTMASTERS_HOUNDS_OTOT(SlayerTask.BEASTMASTERS_HOUNDS, "otot", "Otot", 4194, 880, 0, "Beastmaster's hound"),
    BEASTMASTERS_HOUNDS_GRAVEYARD_MAZCAB(SlayerTask.BEASTMASTERS_HOUNDS, "graveyard_mazcab", "Graveyard (Mazcab)", 4250, 775, 0, "Beastmaster's hound"),
    MOGRES_MUDSKIPPER_POINT(SlayerTask.MOGRES, "mudskipper_point", "Mudskipper Point", 2994, 3111, 0, "Mogre");
    private final SlayerTask task;
    private final SlayerTaskLocation location;

    SlayerTaskLocationDefinition(SlayerTask task, String key, String displayName, int x, int y, int z, String... monsterNames) {
        this.task = task;
        this.location = new SlayerTaskLocation(
                key,
                displayName,
                new Coordinate(x, y, z),
                monsterNames == null || monsterNames.length == 0
                        ? SlayerTaskMonsterRegistry.getDefaultMonsterNames(task)
                        : List.of(monsterNames)
        );
    }

    SlayerTask getTask() {
        return task;
    }

    SlayerTaskLocation getLocation() {
        return location;
    }
}
